Featureforms micro-app update to cache portalitems
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #107
Opened 2023-08-26 00:02 UTC by kaushikrw

2023-08-31 00:16 UTC, sorenoid requested changes
This looks really good. I have just one concern and some small nitpicks. My concern is about the `portalItemFlow` in the `PortalItemRepository`. Please see my question inline.

2023-08-31 00:16 UTC, sorenoid commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/data/network/ItemRemoteDataSource.kt
> +        return@withContext itemApi.fetchItems()
could just be

```suggestion
       itemApi.fetchItems()
```

2023-08-31 00:16 UTC, sorenoid commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/data/PortalItemRepository.kt
> +        itemRepository.observe().mapLatest {
what happens if the item repo grows so large that the first item is loaded and cached (i.e it is emitted by the call to `observe()`)  before the last item begins emitting? Will there be two emissions, one for that first item and one for the last item?

this is my only real concern with this PR. everything else is just nitpicks.

2023-08-31 00:56 UTC, sorenoid commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/data/ItemRepository.kt
> +        localDataSource.deleteAndInsert(localItems + remoteItems)
I see the `@Transaction` annotation on `deleteAndInsert`, which I assume means that the call is thread safe, in addition to indicating that it is a transactional "all or nothing" operation I just want to make sure that this is true and that the calls to `refreshLocalItems` and `remoteDataSource.fetchItemData()` are also thread safe?

2023-08-31 16:27 UTC, kaushikrw commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/di/PersistenceModule.kt
> +            context.applicationContext,
I think `context.applicationContext` is redundant, changed it to just `context`.

2023-08-31 17:30 UTC, kaushikrw commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/data/ItemRepository.kt
> +        localDataSource.deleteAndInsert(localItems + remoteItems)
Yes, that is true. All operations defined on the room `Dao` interfaces are thread-safe. Since the source of data is always reactive to database changes which are observed via flows I believe `datasource.refresh()` should be both thread and main safe. 

I think there is no need for any additional synchronization based on my testing. Perhaps there could be a mechanism to only perform a single `refresh` to prevent duplicate fetches but this operation would ultimately result in synchronized writes to the db and such 'single refresh' is implemented in the UI layer.

2023-08-31 19:06 UTC, kaushikrw commented
@sorenoid Thanks for the feedback. I merged in #110 and its ready for another look!

2023-09-01 02:23 UTC, sorenoid approved these changes
There are a couple small inconsistencies in the use or `return` in `withContext` that should be straightened out. Other than that this looks good. Please see my private message about the SDK work that needs to be merged before this can be merged.

2023-09-01 02:23 UTC, sorenoid commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/data/PortalItemRepository.kt
> +        return@withContext itemCacheDao.getCount()
```suggestion
    itemCacheDao.getCount()
```

2023-09-01 02:23 UTC, sorenoid commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/data/PortalItemRepository.kt
> +            return@withContext file.absolutePath
```suggestion
    file.absolutePath
```

2023-09-07 16:28 UTC, merged