small today fix
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #124
Opened 2023-09-13 02:54 UTC by sorenoid

I didn't fully test the today function when fixing min/max validation...it was broken when the initial date value is not null (and also lots of other ways that don't manifest in our UI). I had only tested on a field that is initially empty.

This fix changes the "today" value to add the offset to arrive at a picker value, instead of subtracting it. It also gets the millis of the ensuing date after that addition so that the millis do not get counted when hours and minutes are derived from it, which happens when the initial date is not null.

2023-09-13 03:07 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/picker/DateTimePicker.kt
> +                datePickerState.setSelection(state.dateTime.value.dateForPicker)
given the `DateTimePicker "now" freeze fix` I am not sure it will still be necessary to set the selection.

2023-09-13 03:09 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/picker/DateTimePicker.kt
> +                datePickerState.setSelection(state.dateTime.value.dateForPicker)
(I tested, it will no longer be necessary).

2023-09-17 23:37 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/picker/DateTimePicker.kt
> +                datePickerState.setSelection(state.dateTime.value.dateForPicker)
```suggestion
```
Yep, don't need to use setSelection anymore.

2023-09-18 19:24 UTC, kaushikrw requested changes
Another issue I found, I guess which is not due to this PR but is evident without incorporating the changes in the comment below, is related to how the `UtcDateTime.hour` and `UtcDateTime.minute` are set and used.

They are set using the constructor but are never used directly. Instead `dateForPicker` and `hourForPicker` are used which are calculate based on the `epochMillis` making the `hour` and `minute` properties redundant.

Hence this behavior can be seen:

If `state.setDateTime()` is called with a date which has a different (hour, minute) than the hour and minute parameters, that former takes precedence when the `TimePicker` is re-composed.

We should probably fix this in a separate issue, but wanted to bring it up.

2023-09-18 19:24 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/picker/DateTimePicker.kt
> +                    timePickerState.minute
Seems like there is double counting happening here with the call to `toDateMillis()`

```
val now = Instant.now().toEpochMilli().toDateMillis()
state.setDateTime(
         now.plus(now.defaultTimeZoneOffset).toDateMillis(),
         timePickerState.hour,
         timePickerState.minute
)
```
This works.
```
val now = Instant.now().toEpochMilli()
state.setDateTime(
        now.plus(now.defaultTimeZoneOffset).toDateMillis(),
        timePickerState.hour,
        timePickerState.minute
)
```

2023-09-18 22:28 UTC, kaushikrw approved these changes

2023-09-19 02:35 UTC, merged