consume event api
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #126
Opened 2023-09-20 02:48 UTC by sorenoid

feature complete but it could use some scrutiny. This PR also includes code for building the SDK from source, and also needs a custom build of runtimecore and the interop.

2023-09-26 18:11 UTC, kaushikrw requested changes

2023-09-26 18:11 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
>          featureForm.getElementValue(formElement)?.toString() ?: ""
Is this still required?

2023-09-28 05:31 UTC, kaushikrw approved these changes
This looks good! Just some minor comments below and a note above.

I think it can merged post those changes so approving it to avoid any delays.

2023-09-28 05:31 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/FeatureForm.kt
> +    var initialEvaluation by remember { mutableStateOf(false) }
@sorenoid I think this still needs to be keyed on `featureForm` so that its reset to false every time a form is opened.

2023-09-28 05:31 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
> +    //val valueChanged: StateFlow<String>
```suggestion
```

2023-09-28 05:31 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextField.kt
> +            // any tap on a blank space will also dismiss the keyboard and clear focusS
```suggestion
            // any tap on a blank space will also dismiss the keyboard and clear focus
```

2023-09-28 05:31 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextField.kt
> +    }
```suggestion
    val label = remember(isRequired) {
        if (isRequired) {
            "${state.label} *"
        } else {
            state.label
        }
    }
```

I think the label need not be a `State` since it's backed by a `State`

2023-09-28 07:08 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextField.kt
> +    }
> I think the label need not be a `State` since it's backed by a `State`

do you mean that since the key's value is delegated to a state variable, there is no need for `label` to be a state variable?

2023-09-28 07:12 UTC, sorenoid commented
thanks for the help @kaushikrw !!

2023-09-28 07:12 UTC, merged