Form field states remember saveable
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #131
Opened 2023-10-02 23:07 UTC by kaushikrw

2023-10-03 22:47 UTC, sorenoid requested changes
Looks good. One question about the lifetime of the CoroutineScope used to restore state objects...

2023-10-03 22:47 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/combo/ComboBoxFieldState.kt
> +                    scope = scope,
Wouldn't this CoroutineScope be cancelled here? It is passed in at object creation time, and then used at object re-creation time, but it most likely comes from a `rememberCoroutineScope()` call?

2023-10-03 22:47 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/combo/ComboBoxFieldState.kt
> + * is called on [ComboBoxFieldState.onValueChanged].
This class can be marked as `@Stable` I think.

2023-10-03 23:01 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/FeatureForm.kt
> +    }
For reasons I don't quite understand, I am seeing different values for `hashCode` when called in `rememberFieldStates()` compared to calling it in the `LazyColumn`. 

Is it safe to assume `fieldName + label + description + hint` is unique for every field?

2023-10-03 23:10 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/FeatureForm.kt
> +    }
really? Maybe we can provide hashCode and equals in a snippet in the SDK, or introduce it in the YAML API design. For this, you might want to try

```java
Objects.hash(fieldName, label, description, hint)
```

just in case one FieldFormElement fieldName is `Foo`, and label `Bar` and some some other FieldFormElement has fieldName `FooBar`, etc.

2023-10-03 23:21 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/combo/ComboBoxFieldState.kt
> +                    scope = scope,
I believe the `Saver( .., scope: CoroutineScope, ..)` is called each time a configuration change occurs, hence the `restore { .. }` block should always recompose with the `CoroutineScope` that is tied to the current composition.

2023-10-03 23:25 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/FeatureForm.kt
> +    }
I think that would be a good idea if we can get that unique identifier for each element from the api.

Thank you for the suggestion, updated!

2023-10-03 23:45 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/combo/ComboBoxFieldState.kt
> +                    scope = scope,
huh. that is not how I thought it worked.

2023-10-04 00:27 UTC, sorenoid approved these changes
very nice!

2023-10-04 00:27 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/combo/ComboBoxFieldState.kt
> +                    scope = scope,
Testing for expression evaluation after configuration changes would be a good way to validate this and it works as expected.

2023-10-04 00:28 UTC, kaushikrw commented
Thanks @sorenoid, merging this!

2023-10-04 00:28 UTC, merged