Sor10874/numeric text field
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #138
Opened 2023-10-05 03:32 UTC by sorenoid

Provides support for numeric types in FormTextField. 

* adds a FieldType and a Domain? property to the BaseFieldState, and the FieldProperties. These are common to all elements, but only used in FormTextField and BaseTextField.
* adds Saver supporting logic for the new properties
* invokes the appropriate keyboard for integer, floating point, or non-numeric input on BaseTextField
* adds some validation strings for numeric inputs, and refactors validation a bit
* extensions on FieldType and platform types to make things a little simpler
* tests
* test refactoring to support FieldProperties (tests were broken).

2023-10-10 16:46 UTC, kaushikrw requested changes
This looks good. The numeric entry is working really well. I had some comments regarding the 
 text validation.

Also, I was unable to get the `FormTextFieldTests` and the `FormTextFieldNumericTests` to run successfully. The former were failing with `Failed to assert the following: (Focused = 'true')` while the latter was failing with `expected:<[Enter value from 1 to 7]> but was:<[This Field Has a Range domain 1-7]>. `
Are you seeing the same behavior?

2023-10-10 16:46 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
> +                }
```suggestion
                    validate(value.value, !isRequired.value)
                }
```
Is there a reason for this change? This would preemptively show all validation errors even for fields that cannot be edited.

2023-10-11 17:47 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
> +                    validate(newValue, true)
the `canBeEmpty` parameter is meant to prevent the "Required" text from showing when editing a required field. We do not run this `validate` unless the field is editable. If the user is editing, the field has focus. The design spec specifically shows that a required, focused, empty field should show the description rather than the "Required" error message.
![Screen Shot 2023-10-11 at 10 24 22 AM](https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/assets/3744900/b58c7cf9-8e23-45ef-9c00-d981f09c1292)



There is a corner case where a field becomes editable as the result of expression evaluation and should therefore be validated immediately. In that case we maybe ought to maintain a property like `wasEditable` and collect on `isEditable` and run validation, similar to what we do for focus changes. But I'd like to make an issue to consider that separately in case it isn't as straight forward as it seems, if that is ok?

2023-10-11 17:47 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
> +                }
fields that cannot be edited are disabled and cannot be focused. Their focus state will never change. If the field is focused, it should not show the "Required" error string according to the design spec.

2023-10-11 18:23 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
> +                    validate(newValue, true)
I think that makes sense. 

There is another case where this would fail, when the value is cleared using the `clear` action button and the field is not focused, it does not trigger required validation.

2023-10-11 20:59 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
> +                }
I have added a change to drop the first value collected from the isFocused StateFlow, so validation doesn't occur preemptively.

2023-10-13 23:17 UTC, kaushikrw requested changes
This looks good. Some small changes might be needed though!

2023-10-13 23:17 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
> +                val numberVal = value.toLong()
```suggestion
                val numberVal = value.toLongOrNull()
```
This could throw an exception if the input is not a number.

2023-10-13 23:17 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
> +                val numberVal = value.toDouble()
```suggestion
                val numberVal = value.toDoubleOrNull()
```
Similarly, here too.

2023-10-16 16:54 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
> +    val supportingText = _supportingText
I agree that the type should be specified, but I don't think this needs to be a computed property does it?

2023-10-16 21:36 UTC, kaushikrw approved these changes
LGTM!

2023-10-16 22:10 UTC, sorenoid commented
thanks @kaushikrw merging!

2023-10-16 22:10 UTC, merged