Forms: Add ComboBox tests
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #141
Opened 2023-10-10 17:21 UTC by kaushikrw

2023-10-11 19:16 UTC, sorenoid requested changes
very nice. just a couple nitpicks.

2023-10-11 19:16 UTC, sorenoid commented on toolkit/featureforms/src/androidTest/java/com/arcgismaps/toolkit/featureforms/ComboBoxFieldTests.kt
> +     * Then the ComboBoxDialog is shown with all coded values AND
The test design doesn't specify that the dialog should show all coded values, and this test doesn't assert it either. I think this part of the comment can be removed. 

It seems like a good subject for a runtimecore unit test to test that all coded values are in the list, but not something that we need to assert in the toolkit.
```suggestion
     * Then a ComboBoxDialog is shown with AND
```

2023-10-16 19:17 UTC, kaushikrw commented
@sorenoid resolved conflicts, ready for another look!

2023-11-08 19:30 UTC, sorenoid approved these changes

2023-11-17 23:14 UTC, merged