Compose Map- graphics overlay
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #158
Opened 2023-10-19 23:54 UTC by shubham7109

2023-10-20 00:37 UTC, puneet-pdx commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/Map.kt
> +    mapOperator: MapOperator,
We don't want to pass the mapOperator to the Map. Internally you should use `LocalMapView ` where ever you are using mapOperator in the Map()

2023-10-20 00:48 UTC, shubham7109 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/Map.kt
> +    mapOperator: MapOperator,
@puneet-pdx Make sense, would it be okay if I were to create an instance of the local of the `LocalMapView` inside of the `Map()` or we should strictly only use the `LocalMapView` 
```kotlin
val mapView = (LocalMapView.current ?: return).apply {
    map = arcGISMap
}
// OR
LocalMapView.current?.map = arcGISMap
```

2023-10-20 00:58 UTC, puneet-pdx commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/Map.kt
> +    mapOperator: MapOperator,
I think the idea is that we create the MapView in the Map if `LocalMapView.current` is null, for the use case when the user does not want to use MapOperator

2023-10-20 01:11 UTC, shubham7109 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/Map.kt
> +    mapOperator: MapOperator,
Updated  👍

2023-10-23 14:16 UTC, gunt0001 requested changes
As discussed, this implementation won't work.

2023-10-23 22:36 UTC, closed without merging