Forms: `DateTimeField` changes
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #161
Opened 2023-10-23 20:54 UTC by kaushikrw

2023-10-23 23:37 UTC, sorenoid requested changes
one small change.

2023-10-23 23:37 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/DateTimeField.kt
> +                    modifier = Modifier.semantics { contentDescription = "description" },
```suggestion
                    text = state.description,
                    modifier = Modifier.semantics { contentDescription = "description" },
                    color = MaterialTheme.colorScheme.onBackground
```

2023-10-23 23:37 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/DateTimeField.kt
> +                    modifier = Modifier.semantics { contentDescription = "description" },
Without this an empty required field has a red description after being edited to be non-empty.

2023-10-24 17:16 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/DateTimeField.kt
> +                    modifier = Modifier.semantics { contentDescription = "description" },
I don't think that should be needed since the `required` and the `description` composable `Text` are different and by default the `description` color would be `LocalContentColor`

2023-10-24 19:50 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/DateTimeField.kt
> +                    modifier = Modifier.semantics { contentDescription = "description" },
I tested it, but now on re-test I don't see it. I must have been incorrect. Never mind!

2023-10-24 19:50 UTC, sorenoid approved these changes
LGTM

2023-10-24 23:13 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/DateTimeField.kt
> +                    modifier = Modifier.semantics { contentDescription = "description" },
That is odd, will keep an eye out if something like this shows up.

2023-10-24 23:14 UTC, kaushikrw commented
Thanks @sorenoid, merging!

2023-10-24 23:14 UTC, merged