consume update value
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #162
Opened 2023-10-23 23:05 UTC by sorenoid

This updates the SDK to 4036 and uses the `formattedValue` when the `valueChanged` event is emitted. There are some known issues with this version of core but I think we can work with it for a weekly build
issue 1: [TreeTrimmingHealthCheck](https://devtopia.esri.com/runtime/apollo/issues/254) map
issue 2: [AdhocUItest_Switch](https://devtopia.esri.com/runtime/apollo/issues/181) map

2023-10-27 02:49 UTC, kaushikrw requested changes
This looks good! The change to use the `codedValue.name` reduced quite a bit of code.

Just some minor nitpicks and a question regarding `DateTimeField` time zone conversion.

2023-10-27 02:49 UTC, kaushikrw commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/screens/map/MapScreen.kt
> +                                Log.w("Forms","applying edits from feature form failed with ${it.message}")
Can we also add a toast here?

2023-10-27 02:49 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/DateTimeFieldState.kt
> +                        value = field.formattedFlow(scope),
It seems like the dates after saving and re-opening are off due to time zone mismatch. Are we planning to fix it separately? I may have forgot what we talked about..

2023-10-30 18:27 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/DateTimeFieldState.kt
> +                        value = field.formattedFlow(scope),
it is being fixed in core.

2023-10-30 18:57 UTC, kaushikrw approved these changes
@sorenoid LGTM!

2023-10-30 18:57 UTC, merged