add inset support
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #182
Opened 2023-11-01 02:59 UTC by puneet-pdx

2023-11-02 14:34 UTC, hud10837 requested changes
Looks good, a few comments

2023-11-02 14:34 UTC, hud10837 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +            mapInsets.calculateEndPadding(layoutDirection).value.toDouble(),
I think it's worth being explicit here, so just to confirm:
- `MapView.setViewInsets` accepts left and right parameters, not start/end.
- By using start/end here, we are essentially adding support for layout direction start/end and doing the swap ourselves. It looks like core does not do any work to handle RTL layouts, so it's okay for us to do this here. But maybe this should be added to doc

2023-11-02 14:34 UTC, hud10837 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +    mapInsets: PaddingValues = PaddingValues(),
Can you add `@param` doc for this?

2023-11-02 14:34 UTC, hud10837 commented on microapps/MapInsetsApp/app/src/main/res/values/themes.xml
Is this file necessary

2023-11-02 14:34 UTC, hud10837 commented on microapps/MapInsetsApp/app/src/main/res/values/colors.xml
Is this file necessary

2023-11-02 14:34 UTC, hud10837 commented on microapps/MapInsetsApp/app/src/main/java/com/arcgismaps/toolkit/mapinsetsapp/screens/MainScreen.kt
> +                        modifier = Modifier.size(96.dp, 64.dp),
Should this also be 90dp?
```suggestion
                        modifier = Modifier.size(90.dp, 64.dp),
```

2023-11-02 21:18 UTC, puneet-pdx commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +            mapInsets.calculateEndPadding(layoutDirection).value.toDouble(),
We are not adding support for layout direction start/end and doing the swap ourselves. The way left/right and start/end works is the other way around for paddingValues. I tested it out Start/End returns the same values when the layout changes from Ltr to Rtl, while left and right values are swapped. 

```Kotlin
/**
 * The padding to be applied along the start edge inside a box: along the left edge if
 * the layout direction is LTR, or along the right edge for RTL.
 */
@Stable
fun PaddingValues.calculateStartPadding(layoutDirection: LayoutDirection) =
    if (layoutDirection == LayoutDirection.Ltr) {
        calculateLeftPadding(layoutDirection)
    } else {
        calculateRightPadding(layoutDirection)
    }

...

@Immutable
internal class PaddingValuesImpl(
    @Stable
    val start: Dp = 0.dp,
    @Stable
    val top: Dp = 0.dp,
    @Stable
    val end: Dp = 0.dp,
    @Stable
    val bottom: Dp = 0.dp
) : PaddingValues {
    override fun calculateLeftPadding(layoutDirection: LayoutDirection) =
        if (layoutDirection == LayoutDirection.Ltr) start else end

    override fun calculateTopPadding() = top

    override fun calculateRightPadding(layoutDirection: LayoutDirection) =
        if (layoutDirection == LayoutDirection.Ltr) end else start

    override fun calculateBottomPadding() = bottom
```
https://androidx.tech/artifacts/compose.foundation/foundation-layout/1.0.0-beta05-source/androidx/compose/foundation/layout/Padding.kt.html

2023-11-02 21:19 UTC, puneet-pdx commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +    mapInsets: PaddingValues = PaddingValues(),
updated

2023-11-02 21:20 UTC, puneet-pdx commented on microapps/MapInsetsApp/app/src/main/res/values/themes.xml
These are generated from the template project and I think we are not removing them. They are included with all the micro app modules. If we want to remove them then we need to decide and remove them everywhere.

2023-11-02 21:20 UTC, puneet-pdx commented on microapps/MapInsetsApp/app/src/main/res/values/colors.xml
These are generated from the template project and I think we are not removing them. They are included with all the micro app modules. If we want to remove them then we need to decide and remove them everywhere.

2023-11-02 21:22 UTC, puneet-pdx commented on microapps/MapInsetsApp/app/src/main/java/com/arcgismaps/toolkit/mapinsetsapp/screens/MainScreen.kt
> +                        modifier = Modifier.size(96.dp, 64.dp),
I reduced the size of others to 90.dp to make room for this one which has longer text that was getting wrapped. I test it again and it seems to work for 90.dp as well. So I have changed it to make them all the same.

2023-11-03 08:21 UTC, hud10837 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +            mapInsets.calculateEndPadding(layoutDirection).value.toDouble(),
I'm pretty convinced then that we should be passing left and right. From what you sent, left and right will abide by start and end

2023-11-06 19:12 UTC, puneet-pdx commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +            mapInsets.calculateEndPadding(layoutDirection).value.toDouble(),
updated

2023-11-07 07:08 UTC, hud10837 approved these changes
👍

2023-11-07 07:09 UTC, hud10837 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +            mapInsets.calculateEndPadding(layoutDirection).value.toDouble(),
🙏

2023-11-07 13:47 UTC, gunt0001 reviewed
@puneet-pdx - looks good, a few comments...

2023-11-07 13:47 UTC, gunt0001 commented on microapps/MapInsetsApp/.gitignore
> +local.properties
The app project needs a readme file with a brief description. See readme for LocationDisplayApp for an example:
https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/blob/feature-branches/geo-compose/microapps/LocationDisplayApp/README.md

2023-11-07 13:47 UTC, gunt0001 commented on microapps/MapInsetsApp/app/src/main/java/com/arcgismaps/toolkit/mapinsetsapp/screens/MainScreen.kt
> +fun MainScreen() {
Needs some doc with a brief description. See LocationDisplayApp for an example:
https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/blob/feature-branches/geo-compose/microapps/LocationDisplayApp/app/src/main/java/com/arcgismaps/toolkit/locationdisplayapp/screens/MainScreen.kt#L54-L61

2023-11-07 21:35 UTC, puneet-pdx commented on microapps/MapInsetsApp/app/src/main/java/com/arcgismaps/toolkit/mapinsetsapp/screens/MainScreen.kt
> +            val focusManager = LocalFocusManager.current
yes, it a Composable invocation can only happen from the context of a composable function. The inline calls are not happening in composable functions.

2023-11-07 21:52 UTC, puneet-pdx commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +    val layoutDirection = LocalLayoutDirection.current
No, it a Composable invocation can only happen from the context of a composable function. The inline calls are not happening in composable functions.

2023-11-07 21:58 UTC, puneet-pdx commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> + * by overlaid UI elements and affecting the MapView's logical center, the reported visible area and the location display.
updated

2023-11-07 21:58 UTC, puneet-pdx commented on microapps/MapInsetsApp/app/src/main/java/com/arcgismaps/toolkit/mapinsetsapp/screens/MainScreen.kt
> +                    )
updated

2023-11-07 22:04 UTC, puneet-pdx commented on microapps/MapInsetsApp/app/src/main/java/com/arcgismaps/toolkit/mapinsetsapp/screens/MainScreen.kt
> +            }
Do we really need to ? We are already remembering the values for left, right, top and bottom text and this is invoked when ever one of the value changes.

2023-11-07 22:04 UTC, puneet-pdx commented on microapps/MapInsetsApp/app/src/main/java/com/arcgismaps/toolkit/mapinsetsapp/screens/MainScreen.kt
> +fun MainScreen() {
added

2023-11-07 22:04 UTC, puneet-pdx commented on microapps/MapInsetsApp/.gitignore
> +local.properties
added

2023-11-09 12:47 UTC, gunt0001 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> + * by overlaid UI elements and affecting the MapView's logical center, the reported visible area and the location display.
remove full stop:
```suggestion
 * by overlaid UI elements and affecting the MapView's logical center, the reported visible area and the location display
```

2023-11-09 12:47 UTC, gunt0001 commented on microapps/MapviewInsetsApp/app/src/main/java/com/arcgismaps/toolkit/mapviewinsetsapp/screens/MainScreen.kt
> +        }
Nitpick - the button could do with some outer padding.

2023-11-09 12:50 UTC, gunt0001 commented
@hud10837 - please take another look once comments are addressed.

2023-11-09 22:14 UTC, puneet-pdx commented on microapps/MapviewInsetsApp/app/src/main/java/com/arcgismaps/toolkit/mapviewinsetsapp/screens/MainScreen.kt
> +        }
added padding

2023-11-09 22:15 UTC, puneet-pdx commented on microapps/MapviewInsetsApp/README.md
> +![Screenshot](screenshot.png)
updated

2023-11-10 10:01 UTC, hud10837 approved these changes

2023-11-10 10:41 UTC, gunt0001 approved these changes

2023-11-13 17:14 UTC, merged