Draw Status
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #186
Opened 2023-11-02 23:42 UTC by shubham7109

PR to implement `DrawStatus` to the Composable `MapView`

2023-11-03 08:45 UTC, hud10837 requested changes

2023-11-03 08:45 UTC, hud10837 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +    drawStatus: ((DrawStatus) -> Unit)? = null,
I think this should be `onDrawStatusChanged`. Otherwise, it looks like the user should be passing in a draw status (although the lambda wouldn't allow that). In the view-based api, it's okay because it's a state flow

2023-11-03 19:32 UTC, shubham7109 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +    drawStatus: ((DrawStatus) -> Unit)? = null,
Makes sense, I've updated the parameter to `onDrawStatusChanged`.

2023-11-03 19:33 UTC, shubham7109 commented
@hud10837, thanks for the feedback. I also would like to slip in a change for `viewpointChanged` to use `Dispatchers.Main.immediate` here. Ready for your review.

2023-11-06 07:36 UTC, hud10837 approved these changes

2023-11-06 07:36 UTC, hud10837 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +        launch(Dispatchers.Main.immediate) {
Thanks for adding this

2023-11-06 10:51 UTC, gunt0001 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +        launch(Dispatchers.Main.immediate) {
`Dispatchers.Main.immediate` is only required for the gesture events. Events raised by Core will always be raised on a Core thread, so we cannot avoid a re-dispatch when collecting on the composition's coroutine context.
```suggestion
        launch() {
```

Same above fore `viewpointChanged`...

2023-11-06 10:51 UTC, gunt0001 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> + * @param onDrawStatusChanged lambda invoked when the draw status of the composable MapView is changed
```suggestion
 * @param onDrawStatusChanged lambda invoked when the draw status of the composable MapView changes
```

2023-11-06 22:55 UTC, shubham7109 commented
Thanks for the feedback. I've reverted the dispatchers change with `viewpointChanged` and `drawStatus` and applied the feedback. Ready for your review. @gunt0001

2023-11-07 10:41 UTC, gunt0001 approved these changes
@shubham7109 - looks good 👍

2023-11-07 16:28 UTC, merged