searchable items map list screen
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #189
Opened 2023-11-03 22:58 UTC by sorenoid

makes the list of maps searchable by title or item id. the title search is case insensitive.

2023-11-06 20:00 UTC, kaushikrw requested changes
Thanks for adding this!

The layout of the search text field looks a little off. It's size and padding do not seem uniform in the top bar. There is a search bar material 3 [design](https://m3.material.io/components/search/overview) that perhaps would be appropriate here, although it might be a bit more work..

<img src="https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/assets/12847934/81350282-e91c-48c0-a7a3-ceed3b7e5e17" width="150">

2023-11-06 20:00 UTC, kaushikrw commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/screens/browse/MapListScreen.kt
> +                            uiState.data.filter {
I think the `MapListViewModel` is the perfect place to hoist the search and filtering instead of here. When the search text changes, a new `MapListUIState` would be emitted with the filtered list.

2023-11-07 00:33 UTC, sorenoid commented
@kaushikrw when we support both agol and enterprise portals I think there will be cause for a navigation icon, and the full search bar and search view design.  I am not sure exactly what you thought was off with the search field. Can you take another look? I've made the layout consistent between landscape and portrait, and made the text box more rounded. I have also hoisted the search text filtering to the view model as suggested.

2023-11-07 17:16 UTC, kaushikrw approved these changes
LGTM!

2023-11-07 17:19 UTC, merged