`Forms` : Microapp SideSheet support
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #207
Opened 2023-11-16 19:23 UTC by kaushikrw

2023-11-16 23:44 UTC, sorenoid requested changes
Looks great! Just some naming feedback. Not sure what I would suggest though

2023-11-16 23:44 UTC, sorenoid commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/screens/bottomsheet/SideSheetLayout.kt
> +fun SideSheetLayout(
This name is a bit misleading. It is the layout for the sheet content when it is centered or when it is on the side.

2023-11-17 01:00 UTC, sorenoid approved these changes
preapproved!

2023-11-17 01:01 UTC, kaushikrw commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/screens/bottomsheet/SideSheetLayout.kt
> +fun SideSheetLayout(
Renamed it to `SheetLayout`.

2023-11-17 01:01 UTC, kaushikrw commented
Thanks @sorenoid, merging.

2023-11-17 01:01 UTC, merged