Erick/web view display proto
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #213
Opened 2023-11-29 00:34 UTC by eri9000

2023-11-30 11:29 UTC, hud10837 requested changes
I like this pattern, some initial thoughts

2023-11-30 11:29 UTC, hud10837 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> +        modifier = modifier,
We should do this to get fullscreen behavior
```suggestion
        modifier = modifier.fillMaxSize(),
```

2023-11-30 11:29 UTC, hud10837 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
>  public fun Authenticator(
This might be a good time to enhance the doc to specify that this displays full screen prompts and @see DialogAuthenticator

2023-11-30 11:29 UTC, hud10837 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> +    onPendingOAuthUserSignIn: ((OAuthUserSignIn) -> Unit)? = null,
I think as part of this PR we should add a modifier argument in the middle which should be there anyway, I discussed with @gunt0001 and this is not a breaking change because the user either has a trailing lambda for `onPendingOAuthUserSignIn` or a named parameter.

2023-11-30 11:29 UTC, hud10837 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> + * @param container if not null, the passed composable will be used as a container for [ServerTrustAuthenticator] and
I know this is a private function, but I think we should be very thorough with the naming and doc here. Perhaps `promptContainer` to be explicit that this container will be used to contain authentication prompts. For the doc, I think we should explicitly mention that the caller must use the argument passed to the lambda in order for authentication prompts to display, otherwise it won't work.

We could also consider naming this something like `onShouldDisplayComposableAuthenticationPrompt`. This way it's explicit that this function is used to display prompts and it will be a bit more obvious what the parameter being passed to it is (ie. an authentication prompt).

2023-11-30 11:29 UTC, hud10837 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> +                it()
I think we should use a named argument here, just to make it clear what's happening

2023-11-30 15:48 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> +private fun AuthenticatorImpl(
Alternative name: 
- AuthenticatorWithContainer
- ContainerAuthenticator

2023-11-30 22:40 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> -            Authenticator(authenticatorState = authenticatorState, modifier = Modifier.fillMaxWidth(), onPendingOAuthUserSignIn)
I removed `fillMaxWidth()` as it doesn't seem to change how the dialogs are displayed.

2023-11-30 22:43 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> + * @param container if not null, the passed composable will be used as a container for [ServerTrustAuthenticator] and
I discussed this with Gunther and we both agreed that `container` describes the behavior. 
I renamed `AuthenticaorImpl` -> `AuthenticatorDelegate`. I am open to suggestions though.

2023-11-30 23:30 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> +        modifier = modifier.fillMaxSize(),
`fillMaxSize()` is needed here otherwise the prompts are displayed at the top of the screen

2023-12-06 14:11 UTC, hud10837 approved these changes
@eri9000 Works as expected on my device. I have some nitpick suggestions, but approving as they don't need re-review

2023-12-07 13:29 UTC, gunt0001 reviewed
@eri9000 - great work. Some doc related comments.

2023-12-07 13:29 UTC, gunt0001 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> + * Displays appropriate Authentication UI when a challenge is issued.
nitpick
```suggestion
 * Displays appropriate Authentication UI when an authentication challenge is issued.
```

2023-12-07 13:29 UTC, gunt0001 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> + * The [ServerTrustAuthenticator] and [UsernamePasswordAuthenticator] components will be displayed in an [AlertDialog].
`ServerTrustAuthenticator` & `UsernamePasswordAuthenticator` are internal types, so we cannot link to them in public doc. Instead I suggest:
```suggestion
 * Server trust prompts and username/password prompts will be displayed in an [AlertDialog].
```

2023-12-07 13:29 UTC, gunt0001 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> + * All other components are displayed in full screen.
```suggestion
 * All other prompts are displayed in full screen.
```

2023-12-07 13:29 UTC, gunt0001 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> + * @param authenticatorState the application viewModel's [AuthenticatorState].
```suggestion
 * @param authenticatorState the object that holds the state to handle authentication challenges.
```

2023-12-07 13:29 UTC, gunt0001 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> + * activity rather than using the [OAuthUserSignInActivity].
```suggestion
 * activity rather than using the [OAuthUserSignInActivity].
 * @see Authenticator
```

2023-12-07 13:29 UTC, gunt0001 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> + * @param authenticatorState the application viewModel's [AuthenticatorState].
```suggestion
 * @param authenticatorState the object that holds the state to handle authentication challenges.
```

2023-12-08 10:32 UTC, gunt0001 approved these changes
@eri9000 - looks good 👍

2023-12-08 22:21 UTC, merged