`Forms`: Refactor Validation
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #276
Opened 2024-01-08 21:26 UTC by kaushikrw

2024-01-10 22:14 UTC, sorenoid requested changes
This looks great but there is a small timing issue between the emission of values and emission of errors.

2024-01-10 22:14 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/base/BaseFieldState.kt
> +    val value: StateFlow<Value<T>> = combine(_mergedValue, _validationError) { newValue, error ->
Based on my understanding of `combine` I would expect to get 2 emissions of this flow every time the `_mergedValue` changes, once when the value actually changes, and again when the validation error changes after calling `filter(validate(newValue))`. The first emission would have an out of date error, and would be incorrect. But that doesn't seem to be happening. I suspect though that the reason it isn't happening is because of the conflated nature of StateFlows, which makes it possible for a collector to miss values if the value changes before the collector is invoked. Placing a 1 second delay above the call to `updateValidation` at line 161 bears this out. So this is only working correctly because of timing.

I think what you want is a flow which emits a `Value`  after the filter method is complete. I am not sure what the best way to do this is. For starters this could become 

```kotlin
val value: StateFlow<Value<T>> = _mergedValue.drop(1).map {
    Value(it, filter(updateValidation(_mergedValue.value))
}.stateIn(
        scope = scope,
        started = SharingStarted.Eagerly,
        initialValue = Value(_mergedValue.value)
    )
```

but this would cut off focus, isEditable, isRequired from updating the UI. One way to solve that is to have all of them emit into the value flow, using concurrent merging of a flow for each. This seems to work but seems overly complicated.

```kotlin
    val _valueFromFocusChange: Flow<Value<T>> = isFocused.drop(1).map {
        Value(_mergedValue.value, filter(validate()))
    }
    
    val _valueFromIsEditableChange: Flow<Value<T>> = isEditable.drop(1).map {
        Value(_mergedValue.value, filter(validate()))
    }
    
    val _valueFromIsRequiredChange: Flow<Value<T>> = isRequired.drop(1).map {
        Value(_mergedValue.value, filter(validate()))
    }
    
    val _valueFromValueChange: Flow<Value<T>> = _mergedValue.drop(1).map {
        Value(it, filter(validate()))
    }
    
    val value: StateFlow<Value<T>> =
        flowOf(
            _valueFromFocusChange,
            _valueFromIsEditableChange,
            _valueFromIsRequiredChange,
            _valueFromValueChange
        ).flattenMerge(concurrency = 4)
            .stateIn(
                scope = scope,
                started = SharingStarted.Eagerly,
                initialValue = Value(initialValue)
            )
  ```

2024-01-10 22:14 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/base/BaseFieldState.kt
> +    }
this would all go away if the concurrent merging suggested above is used.

2024-01-11 18:53 UTC, sorenoid approved these changes
after discussion I resolved my suggestion based on the synchronous and asynchronous nature of input and error validation.

I have some minor cleanup suggestions. happy to approve!

2024-01-11 18:53 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/base/BaseFieldState.kt
> +    private val _validationError: MutableStateFlow<ValidationErrorState> =
`_validationError` seems a bit misleading since it provides a singular error to display in the UI, same with the property in the `Value` class. Can you please add some doc to this effect, and if you can think of an appropriate name that describes its role please consider changing the name here and in the `Value` class. I can't think of a great name, but something like `_errorToDisplay`

2024-01-11 18:53 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/base/BaseFieldState.kt
> +    protected val _mergedValue: StateFlow<T> = flowOf(_value, properties.value)
```suggestion
    @Suppress("PropertyName")
    protected val _mergedValue: StateFlow<T> = flowOf(_value, properties.value)
```

2024-01-11 18:53 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/base/BaseFieldState.kt
> +    protected val _mergedValue: StateFlow<T> = flowOf(_value, properties.value)
there are a few more protected backing properties that could use this annotation, but they aren't part of this diff, such as `_value`.

2024-01-12 23:00 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/base/BaseFieldState.kt
> +    private val _validationError: MutableStateFlow<ValidationErrorState> =
as discussed this will be going away in #287

2024-01-12 23:00 UTC, merged