Update geometry editor symbology
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #289
Opened 2024-01-12 11:59 UTC by Luiy0

**Issue(s)**
[2062](https://devtopia.esri.com/runtime/bistromath/issues/2062)

**Description of change**
Create helper method that applies feature symbology to the geometry editor while the feature is being edited. 

To test with data that doesn't have a feature form definition, remove the feature form non-null requirement in the `FeatureEditorAppState.onSingleTapConfirmed()` and `FeatureEditor.start()`. If the feature geometry is not allowed to be edited, comment the appropriate line when the feature editor is initialised, see [issue](https://devtopia.esri.com/runtime/bistromath/issues/2191). 

**Testing**
Manual testing with a variety of web maps linked in the issue.

2024-01-15 12:42 UTC, fpearson1111 reviewed
Nice work, I have a few comments but the overall approach looks good to me

2024-01-15 12:42 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val opaqueFillColor = Color.fromRgba(featureSymbol.color.component2(), featureSymbol.color.component3(), featureSymbol.color.component4())
It would be better to use the `red`, `green` and `blue` properties on `featureSymbol.color` instead of these component functions -- they are more for enabling destructuring such as
```kotlin
val (a, r, g, b) = myColor
```

2024-01-15 12:42 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val symbolStrokeWidth = (featureSymbol.symbolLayers[1] as StrokeSymbolLayer).width.toFloat()
Will this data always be at index 1 in the symbol layers?

2024-01-15 12:42 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                is PictureMarkerSymbol -> {
Hmm I am a bit confused about this case as I thought PictureMarkerSymbol only applied to points and multipoints. What does it mean for a PictureMarkerSymbol to be used with a polygon? Also should there be a PictureMarkerSymbol case for when the geometry is a point/mulitpoint?

2024-01-15 12:42 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    feedbackLineSymbol = SimpleLineSymbol(SimpleLineSymbolStyle.Dash, featureSymbol.toMultilayerSymbol().color ,width = featureSymbol.toMultilayerSymbol().size/5)
```suggestion
                    feedbackLineSymbol = SimpleLineSymbol(SimpleLineSymbolStyle.Dash, featureSymbol.toMultilayerSymbol().color, width = featureSymbol.toMultilayerSymbol().size/5)
```

2024-01-15 12:42 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val midVertex = SimpleMarkerSymbol(color = Color.white , style = SimpleMarkerSymbolStyle.Circle, size = featureSymbol.toMultilayerSymbol().size/3)
```suggestion
                    val selectedVertex = SimpleMarkerSymbol(color = Color.white, style = SimpleMarkerSymbolStyle.Circle, size = featureSymbol.toMultilayerSymbol().size)
                    val midVertex = SimpleMarkerSymbol(color = Color.white, style = SimpleMarkerSymbolStyle.Circle, size = featureSymbol.toMultilayerSymbol().size/3)
```

2024-01-15 12:42 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    feedbackLineSymbol = SimpleLineSymbol(SimpleLineSymbolStyle.Dash, featureSymbol.toMultilayerSymbol().color ,width = featureSymbol.toMultilayerSymbol().size/5)
Not sure about using the size of the PictureMarkerSymbol to work out a size for the feedback line symbol as they don't really seem like related things. I would be more in favour of using the same size in all cases, maybe taken from the default line symbol that's given by the geometry editor?

2024-01-15 12:42 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +        geometryEditor.tool.style.apply {
Just noting that this geometry editor is passed in by the user so in principle they may have already done some stuff to the style, which could change the effect of this method. I wouldn't really say that's a problem because we can just document it, and probably almost all users will start with a fresh geometry editor.

We could consider whether we want the feature editor to create a new geometry editor when it is created, and then get the user to set that one onto the MapView they are using, rather than what we are currently doing. But that would be part of a separate issue.

2024-01-15 12:44 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val opaqueFillColor = Color.fromRgba(featureSymbol.color.component2(), featureSymbol.color.component3(), featureSymbol.color.component4())
Also does this thing about needing to make the colour opaque apply to lines and points too?

2024-01-16 17:30 UTC, shellygill requested changes
I've added a few comments to be going on with. I think my own lack of knowledge about the details of CIM symbology may be limiting me, and perhaps your own testing @Luiy0 can explain some of FInlay's questions about the types of symbol used for different geometries.

2024-01-16 17:30 UTC, shellygill commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    feedbackVertexSymbol = featureSymbol
I agree this could be a potential enhancement, but low priority.

In some Esri apps, they dont actually have the equivalent of a `selectedVertexSymbol`, as there's no real notion of a selected symbol - the UI just responds to whatever you interact with. In our `GeometryEditor` the option is there for users to use though if that's the behaviour they want, and the selected symbol is differentiated by default. The selected vertex is differentiated visually already by the selection halo, so the user doesnt actually miss any crutial information by not seeing a different `selectedVertexSymbol` hence low priority. (It might be a matter of opinion/taste as to whether you prefer differentiating all the symbols or not). I *think* that the default symbols might acutally be the same for `vertexSymbol` and `selectedVertexSymbol` and also `feedbackVertexSymbol` but would need to confirm that for sure....).

2024-01-16 17:30 UTC, shellygill commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                is PictureMarkerSymbol -> {
PictureMarkerSymbol and SimpleMarkerSymbol are both instances of MarkerSymbol, so it seems to me that these cases could be combined. In face, given that there is no differentiation between how these different cases are treated (`featureSymbol` is always assigned to two properties and the other set to null), I'm not sure of the benefit of checking the symbol type at all. If the symbol is currently being used to symbolise a `Point` feature, then I'd think that same symbol could safely be used to symbolise the `Point`s that comprise our geometry editor style properties that also draw a point. That would then remove the issue of the default symbology below? Worth testing with your known cases, but I'm not sure conceptually I know any reason why this should not work.

2024-01-16 17:30 UTC, shellygill commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val symbolStrokeWidth = (featureSymbol.symbolLayers[0] as StrokeSymbolLayer).width.toFloat()
I would have thought that won't always be the case - I think multilayer symbols might be a collection in any order, based on how the user wanted to create things? [This web app](https://sagewall.github.io/symbol-builder/cim-symbol/) can help you experiement to understand things a bit (I dont find it great for usability but good for a bit of random symbol hacking....).

2024-01-16 17:30 UTC, shellygill commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    feedbackLineSymbol = SimpleLineSymbol(SimpleLineSymbolStyle.Dash, color = featureSymbol.color, width = featureSymbol.width)
👍 I think this is a really good addition - taking colout and width from the existing symbol but making it the familiar dash line style for feedback.

2024-01-16 17:30 UTC, shellygill commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    vertexSymbol = SimpleMarkerSymbol(color = featureSymbol.color, style = SimpleMarkerSymbolStyle.Circle, size = vertexWidth)
> but adds a halo around selected vertices

The halo (AFAIK) is just built-in, based on the internal graphics layer graphic members being `selected` state.

2024-01-16 17:30 UTC, shellygill commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val midVertex = SimpleMarkerSymbol(color = Color.white, style = SimpleMarkerSymbolStyle.Circle, size = midVertexSize)
With CIM symbols, I'm not sure how you'd be able to tell if a marker is used for vertices, vs being used as a repeating symbol along the line - it might be there in the API somewhere but I've not used it enough to know. Worth adding to a 'potential enhancements' followup but probably not worth holding this first PR for is my take.

2024-01-16 17:30 UTC, shellygill commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    vertexSymbol = SimpleMarkerSymbol(color = featureSymbol.color, style = SimpleMarkerSymbolStyle.Circle, size = vertexSize)
Potentially could refactor out these repeated code chunks setting vertexSymbol, etc (might be a kotlin toolkit code style question though...).

2024-01-16 17:30 UTC, shellygill commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    lineSymbol = featureSymbol // Could be null (no outline)
It it that the internals of the geometry editor code do something special with the symbols here, and just take the outline if it's a fill symbol? (Not sure, I think that someone mentioned that - possibly yourself @Luiy0 ?)

2024-01-18 10:46 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +    val featureSymbol = renderer?.getSymbol(feature, true)
The method currently relies on `featureSymbol` not being null but if it is then I agree that we should exit early. We would then use default symbology from the geometry editor. Should the feature editor have different default symbology to that of the geometry editor?

2024-01-18 11:03 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val midVertex = SimpleMarkerSymbol(color = Color.white, style = SimpleMarkerSymbolStyle.Circle, size = midVertexWidth)
It was mostly personal preference since I find the squares to be too bulky and noticeable. AGOL uses circles while Pro uses hollow squares. This brings me back to the question above about the feature editor having its own default symbology.

2024-01-18 12:28 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val midVertexWidth = if (featureSymbol.width < 2) featureSymbol.width * 7 else featureSymbol.width * 2
Originally, line width comparisons were made against a width of one as you suggest but I recall that for width values of around 1.3, the vertices would still appear too small hence why I increased the comparison value. I had to use two different multiplayers depending on the line width to maintain proportionality between line and vertex/midVertex. 

As an example, if a line width is 0.86, the above suggestion would make the vertex appear too small. We could change the multiplier to 10 but that would not work for a line feature with a width of 2.66. I'm not sure if comparing with a value of two this way is the better option but it got me closer to the results I was expecting.

2024-01-18 13:53 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val symbolStrokeWidth = (featureSymbol.symbolLayers[0] as StrokeSymbolLayer).width.toFloat()
I would think that because these are multilayer symbols, they must have at least one symbol layer which most likely corresponds to the geometry they are designed to render. The line features I've been working with don't contain vertices which agrees with the symbol not having a markerLayer and only a strokeLayer at `symbolLayers[0]`. For other complicated multilayerSymbols this order wouldn't necessarily work since it depends on the available layers which I assume follow the order in [this](https://developers.arcgis.com/net/api-reference/api/netwin/Esri.ArcGISRuntime/Esri.ArcGISRuntime.Symbology.SymbolLayer.html#:~:text=The%20following%20table%20lists%20symbol%20types%20and%20symbol%20layers%3A) table or perhaps the order in which they are applied. However, the Qt documentation also states [here](https://developers.arcgis.com/qt/cpp/api-reference/esri-arcgisruntime-multilayersymbol.html#:~:text=Note%3A%20Symbol%20layers%20in%20a%20multilayer%20symbol%20are%20in%20reverse%20order%20of%20how%20they%20appear%20in%20the%20JSON%20representation.):

> Symbol layers in a multilayer symbol are in reverse order of how they appear in the JSON representation.

2024-01-18 13:53 UTC, shellygill commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    vertexSymbol = SimpleMarkerSymbol(color = featureSymbol.color, style = SimpleMarkerSymbolStyle.Circle, size = vertexWidth)
> Following from what was done in AGOL, a vertex changes to white when selected and back to the original colour when unselected

It sounds like the white color change is their equivalent of our selection halo indicating the "current selection", so I don't see a specific need to emulate the color change too.

A lot of these decisions are very subjective though, so I wouldnt spend too much time worrying about the finer detail personally. If such logic were to be pushed down into core for example, I'd imagine that we would want to validate / review most of the choices made, and also really make sure we understand what we're most likely to encounter in terms of CIM symbology (perhaps by discussing with whatever feature team knows that area).

2024-01-18 14:15 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val midVertex = SimpleMarkerSymbol(color = Color.white, style = SimpleMarkerSymbolStyle.Circle, size = midVertexSize)
It's likely possible to get vertex symbology from a markerLayer and it's probably straightforward if the only symbology contained in this layer is reserved for vertices. If not, then the symbology could refer to other things at arbitrary locations along lines, outlines, or within areas.

2024-01-18 14:54 UTC, shellygill commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val midVertex = SimpleMarkerSymbol(color = Color.white, style = SimpleMarkerSymbolStyle.Circle, size = midVertexSize)
> It's likely possible to get vertex symbology from a markerLayer and it's probably straightforward if the only symbology contained in this layer is reserved for vertices.

The symbol must contain the information required to decide whether to apply the marker symbol to vertices, or to locations along the line - how is that expressed in the API @Luiy0 ?

2024-01-18 15:31 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    lineSymbol = featureSymbol // Could be null (no outline)
I'm not sure how this internally works but it has worked for all the features that I've tested with and it's also simpler than creating a SimpleLineSymbol. I also ended up preferring it as to not enforce an outline on a feature that doesn't have one because it can appear strange. I became more aware of this when trying to decide on the size and colour of the outline.

2024-01-18 15:52 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val opaqueFillColor = Color.fromRgba(featureSymbol.color.component2(), featureSymbol.color.component3(), featureSymbol.color.component4())
I think it's unusual for point or line features to have a translucent colour. This colour breakup was only necessary because of polygon fills usually being translucent and we needed to use this colour for the vertices since it didn't have any. I suppose it applies but I'm unsure if the unlikeliness of it happening means we could ignore it?

2024-01-18 15:54 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val symbolStrokeWidth = (featureSymbol.symbolLayers[1] as StrokeSymbolLayer).width.toFloat()
I can't say for certain.

2024-01-18 16:01 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                is PictureMarkerSymbol -> {
Yeah, this is an odd one to edit which I tested with [this](https://runtimecoretest.maps.arcgis.com/home/item.html?id=9452f271998742d6b0b6a8a4cffb234c) webmap. The feature geometry comes back as a polygon yet it's represented by a picutreMarkerSymbol which I had to convert to a multilayerPointSymbol because getting information from the image was a bit complicated. There is a case for point/multipoint.

2024-01-18 16:08 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    feedbackLineSymbol = SimpleLineSymbol(SimpleLineSymbolStyle.Dash, featureSymbol.toMultilayerSymbol().color ,width = featureSymbol.toMultilayerSymbol().size/5)
The size in this case comes from a multilayer point symbol. The other only size I can get is from the width/height of the image. I would still have to resize the default line you suggest depending on the point symbol for proportion.

2024-01-18 16:32 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                is PictureMarkerSymbol -> {
Agreed. Works fine, thanks!

2024-01-18 16:38 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    vertexSymbol = SimpleMarkerSymbol(color = featureSymbol.color, style = SimpleMarkerSymbolStyle.Circle, size = vertexSize)
I could create one SimpleMarkerSymbol but it'll most likely have to be resized after creation as the midVertex is just a bit smaller.

2024-01-19 13:56 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val midVertex = SimpleMarkerSymbol(color = Color.white, style = SimpleMarkerSymbolStyle.Circle, size = midVertexSize)
From Pro documentation [here](https://pro.arcgis.com/en/pro-app/3.1/help/mapping/layer-properties/position-and-place-marker-symbol-layers.htm#:~:text=When%20a%20marker,geometry%20type%20only.):

> When a marker symbol layer is included in a line or polygon symbol, it includes a marker placement, which determines how and where the symbol positions the markers relative to the feature geometry. Marker symbol layers in a point symbol do not have a marker placement; they are always placed relative to the point geometry. There are a number of marker placements to choose from. Most are valid in both line and polygon symbols, but some are valid in one geometry type only.

We should be able to access the `SymbolAnchor`and `SymbolAnchorPlacementMode` through the `MarkerSymbolLayer`.

2024-01-19 14:11 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    feedbackLineSymbol = SimpleLineSymbol(SimpleLineSymbolStyle.Dash, featureSymbol.toMultilayerSymbol().color ,width = featureSymbol.toMultilayerSymbol().size/5)
>  I would still have to resize the default line you suggest depending on the point symbol for proportion.

Ah okay, I think I understand the reason for this a bit better now. Happy to keep it as it is :)

2024-01-19 17:12 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val midVertexWidth = if (featureSymbol.width < 2) featureSymbol.width * 7 else featureSymbol.width * 2
I've updated this to use max and so far it has worked well. Thanks.

2024-01-19 17:13 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    vertexSymbol = SimpleMarkerSymbol(color = featureSymbol.color, style = SimpleMarkerSymbolStyle.Circle, size = vertexWidth)
Updated for feature to remain with the same colour when selected (midVertices are still white).

2024-01-19 17:14 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val symbolStrokeWidth = (featureSymbol.symbolLayers[0] as StrokeSymbolLayer).width.toFloat()
Filtering works well, thanks.

2024-01-19 17:14 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    val opaqueFillColor = Color.fromRgba(featureSymbol.color.component2(), featureSymbol.color.component3(), featureSymbol.color.component4())
Using opaque colours all around now! Thanks.

2024-01-23 11:45 UTC, fpearson1111 reviewed
Few more small comments ☺️

2024-01-23 11:45 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    if (strokeSymbolLayer != null) {
This approach looks good but I think I was being a bit pessimistic in my comment by saying that if this is null then we need to fall back to default symbology. Since this layer is only being used to work out the sizes of various lines and vertices, I think it would make sense to use default values for those sizes if this symbol is null, for example by having a default value for `symbolStrokeWidth`. Same applies to the polygon case.

2024-01-23 11:45 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
>                          outlineColor = it.color
Could also be made opaque?

2024-01-23 11:45 UTC, fpearson1111 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                            color = featureSymbol.color.opaque ,
```suggestion
                            color = featureSymbol.color.opaque,
```

2024-01-23 13:19 UTC, Luiy0 commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +                    if (strokeSymbolLayer != null) {
Updated.

2024-01-23 18:31 UTC, shellygill commented on toolkit/featureeditor/src/main/java/com/arcgismaps/toolkit/featureeditor/FeatureEditor.kt
> +    val featureSymbol = renderer?.getSymbol(feature, true)
I don't think we should come up with a separate default set of symbology for the feature editor at this point, no. If we were to come up with a new set of default GeometryEditor geometry then I think we'd need to be clear on what would be informing the decisions about that default set of symbology, and I don't feel like we know a default set of feature symbology that would be a better set of symbols to follow there, as symbology is so varied and so specific to the data and map. Let me know if my thinking is off here and you did have a specific set of symbols in mind though. To my thinking, possibly there would never be a better set of default symbology. But equally possibly it does become obvious that we should switch to a different specific set of default symbols - and if so then we can come back to this idea when that becomes clear. Until then, there's a default set of symbology for the geometry editor that, while it might not look great for all cases of existing feature geometry, does the job.

2024-01-25 10:29 UTC, fpearson1111 approved these changes
LGTM

2024-01-25 11:57 UTC, merged