Deprecate composable-map
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #293
Opened 2024-01-18 02:37 UTC by puneet-pdx

2024-01-18 09:03 UTC, hud10837 requested changes
Apps work as expected, I just think we should add deprecation warnings to everything

2024-01-18 19:35 UTC, puneet-pdx commented on toolkit/composable-map/src/main/java/com/arcgismaps/toolkit/composablemap/ComposableMap.kt
> +@Deprecated("Use the new composable MapView fun available in the geo-compose toolkit component instead")
I don't know if we want to add the annotation to all individual components that are used with the `ComposableMap` function. We have added the deprecation notice to the module readme and to the main component in the module. I think that should be enough.
@rchintapalli @gunt0001

2024-01-18 19:36 UTC, puneet-pdx commented on toolkit/composable-map/src/main/java/com/arcgismaps/toolkit/composablemap/ComposableMap.kt
> +@Deprecated("Use the new composable MapView fun available in the geo-compose toolkit component instead")
I have updated it to say `function`

2024-01-22 13:50 UTC, hud10837 approved these changes
Approving this so we can get it in before holistic, but I think we should still consider the other deprecations.

2024-01-22 22:53 UTC, puneet-pdx commented
> Approving this so we can get it in before holistic, but I think we should still consider the other deprecations.

@hud10837 I have added other deprecations

2024-01-24 05:42 UTC, eri9000 commented on microapps/FloorFilterApp/app/src/main/java/com/arcgismaps/toolkit/floorfilterapp/screens/MainScreen.kt
> +                else -> {}
Log something to the screen instead?

2024-01-24 16:57 UTC, eri9000 approved these changes
a few things, otherwise LGTM

2024-01-24 17:51 UTC, puneet-pdx commented on microapps/FloorFilterApp/app/src/main/java/com/arcgismaps/toolkit/floorfilterapp/screens/MainScreen.kt
> +                else -> {}
That won't be of any help, as the third FloorFilterSelection.Type is FloorLevel and we are not setting the viewpoint related to the level for this example. This block is just to show the user how they can refocus the viewpoint of the map to the selected site and facility. We left the level out of it.

2024-01-24 17:53 UTC, merged