`Forms`: Attachments API
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #313
Opened 2024-02-07 00:46 UTC by kaushikrw

2024-02-09 19:28 UTC, sorenoid requested changes
a couple questions about missing api prototypes.

2024-02-09 19:28 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/api/AttachmentFormElement.kt
should this class include `fetchAttachmentsAsync()` and `deleteAttachmentAsync()` prototypes?

2024-02-09 19:28 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/api/AttachmentFormElement.kt
> +internal class FormAttachment(
does this class need a prototype of `setName()`?

2024-02-12 20:45 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/api/AttachmentFormElement.kt
> +internal class FormAttachment(
Since the SDK does not expose any public method/property to set the attachment name I did not include it. Would you prefer the api `setName()` is present but it does not do anything?

2024-02-13 01:05 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/api/AttachmentFormElement.kt
added `fetchAttachmentsAsync()`

2024-02-13 04:30 UTC, sorenoid approved these changes
👍

2024-02-13 04:41 UTC, merged