Revisit GraphicsOverlayCollection, AnalysisOverlayCollection and ImageOverlayCollection
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #320
Opened 2024-02-14 01:10 UTC by puneet-pdx

- Rollsback the updating of overlay collections by reference and implements them by just passing Array of overlays as parameter to the function 
- removes custom collection classes
- updates micro app

Adhoc testing code snippets - 
<details>
<summary>SceneView AnalysisOverlay</summary>
@Composable
fun MainScreen() {
    val arcGISScene = remember { ArcGISScene(BasemapStyle.ArcGISImagery) }
    // initialize the viewpoint
    val camera = Camera(Point(-73.0815, -49.3272, 4059.0, SpatialReference.wgs84()), 11.0, 62.0, 0.0)
    var viewpointOperation by remember { mutableStateOf<SceneViewpointOperation?>(SceneViewpointOperation.SetCamera(camera)) }

    // add base surface for elevation data
    val surface = Surface()
    surface.elevationSources.add(
        ArcGISTiledElevationSource(
            "https://elevation3d.arcgis" +
                    ".com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer"
        )
    )
    arcGISScene.baseSurface = surface

    // create an analysis overlay for the line of sight
    val analysisOverlay = AnalysisOverlay()
    val analysisOverlayCollection = remember { arrayOf<AnalysisOverlay>(analysisOverlay) }
    // initialize a line of sight analysis and add it to the analysis overlay
    val observerLocation =
        Point(-73.06958032962375, -49.253112971555446, 2000.0, SpatialReference.wgs84())
    val targetLocation =
        Point(-73.079266999709162, -49.300457676730559, 1312.0, SpatialReference.wgs84())
    val lineOfSight = LocationLineOfSight(observerLocation, targetLocation)
    analysisOverlay.analyses.add(lineOfSight)
//    analysisOverlayCollection.add(analysisOverlay)

        Box(
            modifier = Modifier.fillMaxSize()
        ) {
            SceneView(
                modifier = Modifier.fillMaxSize(),
                arcGISScene = arcGISScene,
                viewpointOperation = viewpointOperation,
                analysisOverlays = analysisOverlayCollection
            )
        }
}
</details>

<details>
<summary>SceneView ImageOverlay</summary>
@Composable
fun MainScreen() {
    val arcGISScene = remember { ArcGISScene(BasemapStyle.ArcGISImagery) }
    // initialize the viewpoint
    val camera = Camera(Point(-73.0815, -49.3272, 4059.0, SpatialReference.wgs84()), 11.0, 62.0, 0.0)
    var viewpointOperation by remember { mutableStateOf<SceneViewpointOperation?>(SceneViewpointOperation.SetCamera(camera)) }

    val point = Point(22.321736, 44.697703, SpatialReference.wgs84())
    val buffered = GeometryEngine.bufferOrNull(point, 30.0)
    val envelope = buffered?.extent
    val imageFrame = ImageFrame("https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/SNice.svg/1200px-SNice.svg.png", envelope!!)
    val imageOverlay = ImageOverlay(imageFrame)
    val imageOverlayCollection by remember { mutableStateOf(arrayOf(imageOverlay)) }

        Box(
            modifier = Modifier.fillMaxSize()
        ) {
            SceneView(
                modifier = Modifier.fillMaxSize(),
                arcGISScene = arcGISScene,
                viewpointOperation = viewpointOperation,
                imageOverlays = imageOverlayCollection
            )
        }
}
</details>

<details>
<summary>MapView Graphics Overlay</summary>
@Composable
fun MainScreen() {
    // create an ArcGISMap with a Topographic basemap style
    val arcGISMap by remember { mutableStateOf(ArcGISMap(BasemapStyle.ArcGISTopographic)) }
    
    val disneyLand_Graphic = Graphic(
        Point(-117.9190, 33.8121, SpatialReference.wgs84()), SimpleMarkerSymbol(
            SimpleMarkerSymbolStyle.Circle, Color.red, 8f))
            
    val disneyLand_Graphic_1 = Graphic(
        Point(-117.9190, 38.8121, SpatialReference.wgs84()), SimpleMarkerSymbol(
            SimpleMarkerSymbolStyle.Circle, Color.red, 8f))
            
     val graphicsOverlay_Point = GraphicsOverlay().apply {
        graphics.add(disneyLand_Graphic)
        }               
        
      var graphicsOverlayArray by remember { mutableStateOf(arrayOf<GraphicsOverlay>(graphicsOverlay_Point)) }  
      // set the composable map's viewpoint to North America
    var mapViewpointOperation: MapViewpointOperation? by remember {
        mutableStateOf(
            MapViewpointOperation.Set(Viewpoint(39.8, -98.6, 10e7))
        )
    }

     Box(
        modifier = Modifier.fillMaxSize()
    ) {
        MapView(
            modifier = Modifier.fillMaxSize(),
            arcGISMap = arcGISMap,
            viewpointOperation = mapViewpointOperation,
             graphicsOverlays = graphicsOverlayArray,
        )

        Button (
            modifier = Modifier
                .padding(25.dp)
                .align(Alignment.BottomEnd),
            onClick = { 
            graphicsOverlayArray = graphicsOverlayArray.plus(GraphicsOverlay().apply {
                    graphics.add(disneyLand_Graphic_1)
                })

            }
        ) {
           Text("Add Graphics")
        }
 }
}
</details>

<details>
<summary>SceneView Graphics Overlay</summary>
@Composable
fun MainScreen() {
val arcGISScene = remember {
        ArcGISScene(BasemapStyle.ArcGISImagery)
    }

    val graphicsOverlay = remember { GraphicsOverlay() }
    val graphicsOverlayCollection by remember { mutableStateOf(arrayOf(graphicsOverlay)) }
    graphicsOverlay.graphics.add(
        Graphic(
            Point(0.0, 0.0, SpatialReference.webMercator()),
            symbol = SimpleMarkerSymbol()
        )
    )

    SceneView(
        modifier = Modifier.fillMaxSize(),
        arcGISScene = arcGISScene,
        graphicsOverlays = graphicsOverlayCollection
    )
}

</details>

2024-02-15 23:35 UTC, shubham7109 approved these changes
Looks good @puneet-pdx. I also tested this using `identifyGraphicsOverlays` which works as expected 👍

2024-02-15 23:35 UTC, shubham7109 commented on microapps/SceneViewCameraControllerApp/app/src/main/java/com/arcgismaps/toolkit/sceneviewcameracontrollerapp/screens/MainScreen.kt
I think this microapp needs to add the changes from #316 to remove `SceneViewpointOperation`

2024-02-16 00:30 UTC, puneet-pdx commented on microapps/SceneViewCameraControllerApp/app/src/main/java/com/arcgismaps/toolkit/sceneviewcameracontrollerapp/screens/MainScreen.kt
@shubham7109 It got missed in that PR I have created another PR that addresses it https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/325

2024-02-21 10:14 UTC, hud10837 requested changes
Looks good, but I think we should remember the default values

2024-02-21 10:14 UTC, hud10837 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +    graphicsOverlays: List<GraphicsOverlay> = emptyList(),
I think this should be remembered so we don't create a new empty list on every recomposition.

```suggestion
    graphicsOverlays: List<GraphicsOverlay> = remember { emptyList() },
```

2024-02-21 10:14 UTC, hud10837 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/SceneView.kt
> +    graphicsOverlays: List<GraphicsOverlay> = emptyList(),
```suggestion
    graphicsOverlays: List<GraphicsOverlay> = remember { emptyList() },
```

2024-02-21 10:14 UTC, hud10837 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/SceneView.kt
> +    analysisOverlays: List<AnalysisOverlay> = emptyList(),
```suggestion
    analysisOverlays: List<AnalysisOverlay> = remember { emptyList() },
```

2024-02-21 10:14 UTC, hud10837 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/SceneView.kt
> +    imageOverlays: List<ImageOverlay> = emptyList(),
```suggestion
    imageOverlays: List<ImageOverlay> = remember { emptyList() },
```

2024-02-21 19:27 UTC, puneet-pdx commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +    graphicsOverlays: List<GraphicsOverlay> = emptyList(),
@hud10837 I went back and forth about this as well and went with not remembering the emptyList() instance as in theory it would not make a difference and also that is how [google maps](https://github.com/googlemaps/android-maps-compose/blob/main/maps-compose/src/main/java/com/google/maps/android/compose/Polygon.kt#L61) had it. 
But to be safe from unintended consequences it makes sense to remember it as that would prevent us from initializing an emptyList() every time a recomposition occurs.

2024-02-22 13:30 UTC, gunt0001 approved these changes
@puneet-pdx - looks good, some minor suggestions

2024-02-22 13:30 UTC, gunt0001 commented on microapps/MapViewGeometryEditorApp/app/src/main/java/com/arcgismaps/toolkit/mapviewgeometryeditorapp/screens/MainScreen.kt
> -    graphicsOverlays: GraphicsOverlayCollection,
Good simplification 👍

2024-02-22 13:30 UTC, gunt0001 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/MapView.kt
> +            if (mapView.graphicsOverlays != graphicsOverlays) {
Better to use `it` for consistency:
```suggestion
            if (it.graphicsOverlays != graphicsOverlays) {
```

2024-02-22 13:30 UTC, gunt0001 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/SceneView.kt
> +            if (sceneView.graphicsOverlays != graphicsOverlays) {
```suggestion
            if (it.graphicsOverlays != graphicsOverlays) {
```

2024-02-22 13:30 UTC, gunt0001 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/SceneView.kt
> +            if (sceneView.analysisOverlays != analysisOverlays) {
```suggestion
            if (it.analysisOverlays != analysisOverlays) {
```

2024-02-22 13:30 UTC, gunt0001 commented on toolkit/geo-compose/src/main/java/com/arcgismaps/toolkit/geocompose/SceneView.kt
> +            if (sceneView.imageOverlays != imageOverlays) {
```suggestion
            if (it.imageOverlays != imageOverlays) {
```

2024-02-22 13:33 UTC, merged