`Forms` Fork date picker
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #321
Opened 2024-02-14 01:55 UTC by kaushikrw

2024-02-14 05:52 UTC, sorenoid requested changes
thanks. looks good, one file name seems mangled though?

2024-02-14 05:52 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/picker/date/DatePickerlTokens.kt
Is this file supposed to be named `DatePickerModalTokens.kt`?

2024-02-14 17:31 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/datetime/picker/date/DatePickerlTokens.kt
Good catch, changed it to `DatePickerTokens`.

2024-02-16 04:09 UTC, sorenoid approved these changes

2024-02-16 16:26 UTC, merged