`Forms` : Consume latest sdk
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #324
Opened 2024-02-16 00:19 UTC by kaushikrw

2024-02-16 04:00 UTC, sorenoid approved these changes
Looks great, thank you.

2024-02-16 18:16 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/utils/CorePrototypes.kt
> +    } else if (value.value is T) {
Yeah. When you clear a `ComboBox` field that is a `string` field type, you have to set the field value to `null`. But since the `ComboBox` requests the `valueFlow` type `T` be a `string`, when the `null` comes around the cast `value as T` will fail.

2024-02-20 00:13 UTC, kaushikrw commented
@sorenoid It's now ready for review!

2024-02-21 20:01 UTC, sorenoid requested changes
Looks great. just one clarification/question and a request to bump the SDK version to today.

2024-02-21 21:07 UTC, sorenoid approved these changes

2024-02-21 21:08 UTC, kaushikrw commented
thanks @sorenoid, merging.

2024-02-21 21:08 UTC, merged