api backwards compatibility validation
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #345
Opened 2024-02-29 03:08 UTC by sorenoid

Adds the use of the Kotlin-JVM binary compatibility validator gradle plugin

adds the `api` file which represents the FeatureForms public API
support for generating the `api` file by running gradle task `apiDump`
support for checking backwards compatibility violations by running gradle task `apiCheck`

2024-03-04 22:20 UTC, kaushikrw requested changes
This plugin seems very helpful for the toolkit, especially as our compose apis become large. 

I was however wondering, what the workflow would be if and when this gets integrated into Github Checks. Perhaps we can document it into a README, how to verify and update the api compatibility.

2024-03-04 22:20 UTC, kaushikrw commented on toolkit/featureforms/build.gradle.kts
> +    ignoredClasses.addAll(composableSingletons)
```suggestion
    ignoredPackages.add("com.arcgismaps.toolkit.featureforms.components")
```
I think the entire package can be ignored.

2024-03-05 15:31 UTC, gunt0001 approved these changes
Looks good 👍

2024-03-05 19:12 UTC, sorenoid commented on toolkit/featureforms/build.gradle.kts
> +    ignoredClasses.addAll(composableSingletons)
> I think the entire package can be ignored. It might be a little tedious to keep track of all the internal compose functions.

@kaushikrw I'd like to discuss this point a bit offline.

2024-03-05 19:56 UTC, kaushikrw commented on toolkit/featureforms/build.gradle.kts
> +    ignoredClasses.addAll(composableSingletons)
As discussed, this can go in now and we will later move all the internal components into an `internal` package for feature forms and ignore that package.

2024-03-05 19:56 UTC, kaushikrw approved these changes
LGTM

2024-03-05 22:01 UTC, merged