feat(localization): update translation
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #349
Opened 2024-03-05 21:22 UTC by jona7150

Updated translation using Jenkins. Please review and merge @sor10874 

 CC: @michi6571 @masa6674

2024-03-15 23:15 UTC, sorenoid requested changes

2024-03-15 23:15 UTC, sorenoid commented on toolkit/authentication/src/main/res/values-ar/strings.xml
> +    <string name="server_trust_message">الشهادة المقدمة من %1$s غير موقعة من قبل مرجع مصدق موثوق.</string>
the format placeholder has been broken here and elsewhere in Arabic translations.

2024-03-15 23:15 UTC, sorenoid commented
@michi6571 @masa6674 Arabic translations appear broken as described in the diff.

2024-03-16 01:07 UTC, michi6571 commented
> @michi6571 @masa6674 Arabic translations appear broken as described in the diff.

@sorenoid Thank you for letting us know.  Please note that Git does NOT show RTL and BiDi correctly.  Could you please check the translation in the product and let us know if you still see the issue?  

cc @jona7150 @masa6674

2024-03-16 02:14 UTC, sorenoid approved these changes
Arabic format strings look ok in the IDE. thanks.

2024-03-16 02:14 UTC, sorenoid commented on toolkit/authentication/src/main/res/values-ar/strings.xml
> +    <string name="server_trust_message">الشهادة المقدمة من %1$s غير موقعة من قبل مرجع مصدق موثوق.</string>
string looks ok when visually inspected in the IDE. The format placeholder is not broken into two pieces. weird.

2024-03-16 02:14 UTC, merged