Feature branches/forms
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #360
Opened 2024-03-16 01:51 UTC by sorenoid

merges the FeatureForms feature branch to v.next.
* FeatureForms toolkit component
    * FeatureForm toolkit API, captured in an [API file](https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/compare/v.next...feature-branches/forms?expand=1#diff-abf396b5ae994999e6ef4dab255146bc3fc8161653c280f3627e6c4064baf320) by the binary compatibility validator plugin.
    * support for Field Elements with TextBox, TextArea, DateTimePicker, ComboBox, Radio, Switch, and Unsupported input types
    * support for Group Elements containing the above Field Elements types as nested elements.
    * support for Unsupported Elements
    * Forked versions of material3 androidx DatePicker and TimePicker with no internal use of experimental API annotations and bug fixes for the TimePicker.
    * UI tests from the runtime/common-toolkit [test design](https://devtopia.esri.com/runtime/common-toolkit/blob/main/designs/Forms/FormsTestDesign.md)
* Modern android architected FeatureForms microapp
    * username/password and enterprise authentication 
    * HiltViewModel
    * PortalItem webmap repository and data sources with persisted, Loaded PortalItems.
    * dependency injection
    * Webmap gallery screen
    * Forked version of material3 androidx BottomSheet with additional sheet states and no use of experimental API annotations

2024-03-16 02:11 UTC, kaushikrw requested changes
LGTM! Just one small comment regarding the since version.

2024-03-16 02:11 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/FeatureForm.kt
> + * @since 200.2.0
```suggestion
 * @since 200.4.0
```
I think we should bump this up to 200.4

2024-03-16 02:18 UTC, kaushikrw approved these changes
👍

2024-03-18 11:05 UTC, gunt0001 approved these changes

2024-03-18 22:22 UTC, merged