`Forms`: Add theming support
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #362
Opened 2024-03-19 02:06 UTC by kaushikrw

2024-04-15 23:16 UTC, sorenoid requested changes
@kaushikrw this looks great and fills a valuable need for FeatureForms. I have some very high level suggestions
* provide a dark mode color palette that is applied automatically when in dark mode
* add since tags to all public API
* provide a simple theme for the FeatureForm itself in addition to the individual components of the form.
    * this theme could be used for the body of GroupElements as well, perhaps with different defaults.

2024-04-15 23:16 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/theme/DefaultThemeTokens.kt
> +private object PaletteTokens {
I think this needs to check `isSystemInDarkTheme()` and offer dark mode alternatives/

2024-04-15 23:16 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/theme/FeatureFormTheme.kt
> +public data class FeatureFormColorScheme internal constructor(
All of the public types, properties and function need to have `since 200.5.0` tags.

2024-04-15 23:31 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/internal/components/base/BaseTextField.kt
> +        // if placeholder is visible, make it lighter than the actual input text color
I don't think we ever created an issue, but this behavior also exists in the pre-custom theme system.

2024-04-15 23:39 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/theme/DefaultThemeTokens.kt
> +private object PaletteTokens {
I'm not sure this is needed. The `DefaultThemeTokens` only needs to provide default values for `LocalColorScheme` and `LocalTypography`. These defaults are only utilized in internal compose previews. During runtime the actual values are always taken from `MaterialTheme`.

2024-04-26 17:37 UTC, kaushikrw commented
@sorenoid I've updated this based on our new design standard and addressed some of the feedback. Please have another look!

2024-04-30 19:35 UTC, sorenoid approved these changes
LGTM!

2024-04-30 20:48 UTC, kaushikrw commented
Thanks @sorenoid, merging.

2024-04-30 20:48 UTC, merged