Update Readmes for geoview-compose
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #370
Opened 2024-03-25 16:15 UTC by hud10837

- Updates readme references for the geoview-compose module
- Adds a note about using maven in the main README
- Updates developer setup with all modules
- Adds api ref links to all toolkit component readmes
- Various small fixes

2024-03-26 01:51 UTC, puneet-pdx reviewed
@hud10837 looks good. Just one question. 

Also as a part of this PR can you please update the link to the geo-compose module in the deprecation notice for Composable Map in its readme to use relative path so it will work both in both main and `v.next`.  
https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/tree/v.next/toolkit/composable-map#composable-mapdeprecated 

https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/355#discussion_r1526682828

2024-03-26 10:30 UTC, hud10837 commented on doc/release/release_process.md
> +a complete set of inter-compatible toolkit components.
Must have done it without thinking, my IDE is highlighting it as needing a hyphen

2024-03-26 10:34 UTC, hud10837 commented
Thanks @puneet-pdx I have made those changes

2024-03-26 15:40 UTC, puneet-pdx approved these changes
@hud10837 LGTM 👍🏽

2024-03-26 19:34 UTC, shubham7109 requested changes
Overall looks good, just have two minor comments:

2024-03-26 19:34 UTC, shubham7109 commented on toolkit/compass/README.md
This compass readme shows a snippet of its usage using `ComposableMap` & `MapInterface`. The micro-app for this module uses geoview-compose `MapView` & `MapViewProxy`.  I think we should update the readme here as well. 

- This comment also applies to the [FloorFilter](https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/tree/hud10837/update-readmes/toolkit/indoors#workflow) readme.

2024-03-26 19:34 UTC, shubham7109 commented on toolkit/geoview-compose/README.md
This list of other examples is missing: **scene-view-analysis-overlay-app**

https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/blob/d5e303ac5d1d7d41ab666d57fd16c31b7d163c56/toolkit/geoview-compose/README.md#L121-L130

2024-03-27 00:01 UTC, puneet-pdx approved these changes

2024-03-27 00:01 UTC, puneet-pdx commented on README.md
> +implementation(platform('com.esri:arcgis-maps-kotlin-toolkit-bom:200.4.0'))
Gradle throws an exception if you use single quotes when specifying the dependencies. We should change these examples to use us qoutes,
```suggestion
implementation(platform("com.esri:arcgis-maps-kotlin-toolkit-bom:200.4.0"))
implementation("com.esri:arcgis-maps-kotlin-toolkit-authentication")
implementation("com.esri:arcgis-maps-kotlin-toolkit-compass")
implementation("com.esri:arcgis-maps-kotlin-toolkit-indoors")
```

2024-03-27 18:55 UTC, shubham7109 approved these changes
@hud10837 Looks good!

2024-03-28 11:32 UTC, hud10837 commented
Thanks @shubham7109 @puneet-pdx

2024-03-28 11:32 UTC, merged