Changes to abstract strings used for accessibility
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #394
Opened 2024-04-16 00:42 UTC by puneet-pdx

I tested the Floorfilter app with the TalkBack feature and kept only the strings that were being used. 

There are some changes that update the formatting

2024-04-16 20:00 UTC, shubham7109 commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/FloorFilter.kt
> -        modifier = modifier.semantics { contentDescription = "FloorFilterComponent" },
The change will break the `FloorFilterTests` instrumented test. Should this also be abstracted to `strings.xml`?

2024-04-16 23:08 UTC, puneet-pdx commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/FloorFilter.kt
> -        modifier = modifier.semantics { contentDescription = "FloorFilterComponent" },
This particular string is not needed. I have modified the test so now it will perform the same test without making use of this.

2024-04-16 23:09 UTC, puneet-pdx commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/FloorFilter.kt
> -        modifier = modifier.semantics { contentDescription = "SiteFacilityButton" }
This is also not needed for the test.

2024-04-16 23:12 UTC, puneet-pdx commented
@shubham7109 I have only kept the strings that makes sense from accessibility/testing point of view. The ones I have weeded out did not make sense from accessibility point of view and also were not needed for the automated test. I have not modified the test steps but just the content strings for the nodes being tested.

2024-04-16 23:13 UTC, puneet-pdx commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/SiteAndFacilitySelector.kt
> +    isSelected: Boolean,
I have shuffled this fun's parameters to match the order in which they are from the only invoking site in the code.

2024-04-16 23:25 UTC, shubham7109 approved these changes
Looks good 👍, just the one comment.

2024-04-16 23:25 UTC, shubham7109 commented on toolkit/indoors/src/main/res/values/strings.xml
> +    <string name="not_available">not available</string>
Not sure, but I think this would need to be capitalized: 
```suggestion
    <string name="not_available">Not available</string>
```

2024-04-23 23:19 UTC, ruiqima approved these changes
LGTM 👍 Tried with TalkBack and it works well. Left one comment.

2024-04-23 23:19 UTC, ruiqima commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/SiteAndFacilitySelector.kt
> +        if (isSiteItem) stringResource(id = R.string.site_item) else stringResource(id = R.string.facility_item)
I tried with TalkBack and this works well with "facility item Azimuth in list". Just curious how we manage to have it read the option's name (e.g. Azimuth), is there a specific rule for TalkBack to do this?

The reason I'm thinking this is, when tapping on a floor level, it only said "floor level select button", without the specific level number. It could be better if we can have it speak out the exact floor number as in the above example. But I'm not sure if we could achieve this or not.

2024-04-23 23:22 UTC, ruiqima commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/SiteAndFacilitySelector.kt
> +        if (isSiteItem) stringResource(id = R.string.site_item) else stringResource(id = R.string.facility_item)
Another interesting behavior for TalkBack I found is, if you swipe up or down on the screen, it may gave you weird english letters. Don't understand what it is doing. But I think this is TalkBack thing, not from our FloorFilter. Just want to share this discovery.

2024-04-24 00:03 UTC, sorenoid requested changes
looks good. just one question.

2024-04-24 00:03 UTC, sorenoid commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/SiteAndFacilitySelector.kt
> +                            ?: stringResource(id = R.string.not_available)),
In a RTL language shouldn't this text be `<name> - Site`? If I understand correctly, then the current string will not be correct in a RTL language, regardless of translation. It seems like the name of the site should be passed into stringResource as a format parameter.
```suggestion
val name =  floorFilterState.getSelectedSite()?.name ?: stringResource(id = R.string.not_available)
Text(
    text = stringResource(R.string.floor_filter_site_selector_top_bar, name)
```

and the string resource should be

```xml
<!-- This text is a label on a text field that displays the name of the site after the hyphen -->
<string name="floor_filter_site_selector_top_bar">Site - %1$s</string>
```

so that it can be translated to a RTL language
```
<string name="floor_filter_site_selector_top_bar">%1$s - Site</string>
```

2024-04-24 23:33 UTC, puneet-pdx commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/SiteAndFacilitySelector.kt
> +        if (isSiteItem) stringResource(id = R.string.site_item) else stringResource(id = R.string.facility_item)
@ruiqima that happens when it starts reading the text on an element. I starts to spell it.

2024-04-24 23:35 UTC, puneet-pdx commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/SiteAndFacilitySelector.kt
> +        if (isSiteItem) stringResource(id = R.string.site_item) else stringResource(id = R.string.facility_item)
also there we are not specifying how TalkBack is reading the list. Maybe we can look into it further for the floor level select button.

2024-04-25 18:11 UTC, puneet-pdx commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/SiteAndFacilitySelector.kt
> +                            ?: stringResource(id = R.string.not_available)),
Good call. Updated

2024-04-26 23:07 UTC, sorenoid approved these changes

2024-04-30 23:16 UTC, puneet-pdx commented
Thanks @sorenoid @shubham7109 @ruiqima. Merging..

2024-04-30 23:16 UTC, merged