`Forms`: Check if map has a FeatureFormDefinition
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #399
Opened 2024-04-18 21:11 UTC by kaushikrw

2024-04-20 17:16 UTC, sorenoid requested changes
Looks good, I suggest one small change

2024-04-20 17:16 UTC, sorenoid commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/screens/map/MapViewModel.kt
> +                it.load()
I don't think it is necessary to load the layer here. The `featureFormDefinition` will be non-null before the layer is loaded if it exists. It could be loaded below in the else case so that only the layer that is needed is loaded explicitly here.

2024-04-22 22:24 UTC, kaushikrw commented on microapps/FeatureFormsApp/app/src/main/java/com/arcgismaps/toolkit/featureformsapp/screens/map/MapViewModel.kt
> +                it.load()
@sorenoid It seems like the layer needs to be loaded at this time. I can update this when that changes.

2024-04-23 00:02 UTC, sorenoid approved these changes
based on the featureFormDefinition's availability before layer loading, approved.

2024-04-23 00:28 UTC, kaushikrw commented
thanks @sorenoid

2024-04-23 00:29 UTC, merged