Erick/text popup element
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #413
Opened 2024-05-01 00:22 UTC by eri9000

2024-05-04 00:28 UTC, sorenoid requested changes
Looks nice. Some small suggestions.

2024-05-04 00:28 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/ExpandableCard.kt
> +
There should probably be a Spacer here.

2024-05-04 00:28 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/ExpandableCard.kt
> +                    IconButton(onClick = { expanded = !expanded }) {
Is IconButton necessary? It seems like an Icon wrapped in a CrossFade animation will work. I think at any rate the animation is necessary.

2024-05-04 00:28 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/ExpandableCard.kt
> +                            imageVector = if (expanded) Icons.Default.KeyboardArrowUp else Icons.Default.KeyboardArrowDown,
I think the carets are not centered in their bitmaps. Better to use `Icons.Rounded.ExpandLess` and `Icons.Rounded.ExpandMore`

2024-05-06 22:01 UTC, eri9000 commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/ExpandableCard.kt
> +
I've added a spaced only when there's a title.

2024-05-06 23:08 UTC, sorenoid approved these changes

2024-05-06 23:22 UTC, merged