`Forms`: Delete & rename attachments
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #417
Opened 2024-05-06 20:31 UTC by kaushikrw

2024-05-08 23:27 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/internal/components/attachment/AttachmentElementState.kt
> +        other as FormAttachmentState
I didn't realize this was possible but it makes sense 👍

2024-05-08 23:27 UTC, sorenoid approved these changes

2024-05-09 21:17 UTC, sorenoid requested changes

2024-05-09 21:17 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/internal/components/attachment/AttachmentElementState.kt
>          onLoadAttachment = attachment::load,
If a Loadable is FailedToLoad state, calling `load()` on it will immediately fail. You must call retryLoad() to load a previously failed Loadable.

```suggestion
        onLoadAttachment = attachment::retryLoad,
```

2024-05-09 21:17 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/internal/components/attachment/AttachmentTile.kt
> +                            state.load()
this needs to invoke `retryLoad()`

2024-05-09 21:45 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/internal/components/attachment/AttachmentElementState.kt
>          onLoadAttachment = attachment::load,
thanks, updated!

2024-05-13 16:28 UTC, sorenoid approved these changes

2024-05-13 16:29 UTC, merged