Add initial implementation and micro app
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #419
Opened 2024-05-07 19:41 UTC by puneet-pdx

2024-05-08 21:16 UTC, shubham7109 approved these changes
Looks good, basic implementation works well and should be perfect to plug-in changes to build a Callout. I would recommend adding an empty `README.md` for the microapp in this PR.

2024-05-08 21:16 UTC, shubham7109 commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/MapView.kt
> +    content: (@Composable MapViewScope.() -> Unit)? = null
Would this need to be defined as a slot-param like using a `calloutContent`? Or would that be added in a future issue?

2024-05-08 22:10 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/MapView.kt
> +    content: (@Composable MapViewScope.() -> Unit)? = null
We are sticking with this for now. This parameter might evolve in the future, it is yet to be determined. Check this space https://devtopia.esri.com/runtime/kotlin/discussions/3976

2024-05-09 17:01 UTC, sorenoid requested changes

2024-05-09 17:30 UTC, puneet-pdx commented on microapps/MapViewCalloutApp/app/build.gradle.kts
> +}
This is included in all the micro apps currently and also part of the template app. We should create an issue to clean it up across all the micro apps if it is not needed ?

2024-05-09 17:42 UTC, puneet-pdx commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/MainScreen.kt
> +}
Would't this classify as code duplication ?

2024-05-09 19:36 UTC, puneet-pdx commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/MainScreen.kt
> +    var mapPoint by remember { mutableStateOf ( null as Point? ) }
With the viewmodel this is not relevant

2024-05-09 19:37 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +package com.arcgismaps.toolkit.geoviewcompose
We can consider it later??

2024-05-10 02:39 UTC, sorenoid requested changes
looks good, but I think the content should be null if the mapPoint is null. A couple other things.

2024-05-10 02:39 UTC, sorenoid commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/MainScreen.kt
> +    ) {
also I don't see the reason for the double tap handler to be set.

2024-05-10 15:14 UTC, puneet-pdx commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/MainScreen.kt
> +    ) {
The double tap handler leaked through.. I have update this

2024-05-10 15:15 UTC, puneet-pdx commented on settings.gradle.kts
> +project(":map-view-callout-app").projectDir = File(rootDir, "microapps/mapviewcalloutapp/app")
a bunch of other micro apps are named this way, which threw me off..

2024-05-10 17:40 UTC, sorenoid approved these changes
👍

2024-05-10 18:26 UTC, puneet-pdx commented
Thanks @sorenoid @shubham7109. Merging..

2024-05-10 18:26 UTC, merged