Callout Shape Path
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #421
Opened 2024-05-08 23:20 UTC by shubham7109

2024-05-14 22:35 UTC, puneet-pdx reviewed
@shubham7109 looks good over all. Some comments regarding doc and some reordering

2024-05-14 22:35 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> + * [cornerRadius] The corner radius of the rectangle shape in px.
```suggestion
 * [cornerRadius] The corner radius of the Callout shape in px.
```

2024-05-14 22:35 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +    val cornerRadius = 10.dp
We should add these values to a defaults object, something like
```Kotlin
public object CalloutDefaults {
   public val minSize = DpSize(
        width = strokeBorderWidth + (2 * cornerRadius),
        height = strokeBorderWidth + (2 * cornerRadius)
    )
    public val cornerRadius = 10.dp
    public val strokeBorderWidth = 2.dp
    public val strokeColor = Color.LightGray
    public val backgroundColor = Color.White
    public val calloutContentPadding = PaddingValues(cornerRadius + (strokeBorderWidth / 2))
    public val leaderWidth = 10.dp
    public val leaderHeight = 12.dp
}
```

2024-05-14 22:35 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> + * Extension function to draw the Callout shape using the given shape options.
Something like..
```suggestion
 * Extension function to draw the Callout using the given parameters. It draws the shape, adds the content padding, adds padding for the leader height, restricting the min size and positions it on the screen. 
```

2024-05-14 22:35 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +    anchorLeaderWidth: Float,
We don't need the anchor prefix

2024-05-14 22:35 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +    anchorLeaderWidth: Float,
also can you arrange these in the order i mentioned for the default values.

2024-05-14 22:35 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +public fun CalloutPreview() {
We can remove this

2024-05-14 22:42 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +
unnecessary newline

2024-05-14 23:06 UTC, shubham7109 commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +    val cornerRadius = 10.dp
This order would not work, since `minSize` depends on `strokeBorderWidth` and `cornerRadius`. I think it would be ideal to use a data class here similar to the FloorFilter's `UIProperties`. 


Lmk if there are any concerns using this: 

```kotlin
/**
 * UI default properties for the [Callout] component.
 */
public data class CalloutProperties(
    public val cornerRadius: Dp = 10.dp,
    public val strokeBorderWidth: Dp = 2.dp,
    public val strokeColor: Color = Color.LightGray,
    public val backgroundColor: Color = Color.White,
    public val calloutContentPadding: PaddingValues = PaddingValues(
        all = cornerRadius + (strokeBorderWidth / 2)
    ),
    public val leaderSize: DpSize = DpSize(
        width = 10.dp,
        height = 12.dp
    ),
    public val minSize: DpSize = DpSize(
        width = strokeBorderWidth + (2 * cornerRadius),
        height = strokeBorderWidth + (2 * cornerRadius)
    )
)
```

2024-05-14 23:28 UTC, shubham7109 commented
@puneet-pdx Thanks for the feedback, I have added them and updated the PR from the feature branch. Ready for your review.

2024-05-15 18:30 UTC, puneet-pdx approved these changes

2024-05-15 21:43 UTC, sorenoid requested changes
Looks great. Just some suggestions around the readiness of the styling API to defensively make it internal until we are ready to release it.

2024-05-15 21:43 UTC, sorenoid commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> + * [calloutScreenCoordinate] Represents the x,y coordinate of the Callout leader.
```suggestion
 * @param cornerRadius The corner radius of the Callout shape in px.
 * @param strokeBorderWidth Width of the Callout stroke in px.
 * @param strokeColor Color used to define the outline stroke.
 * @param backgroundColor Color used to define the fill color of the Callout shape.
 * @param calloutContentPadding PaddingValues for the content placed inside the Callout.
 * @param leaderWidth Width of the Callout leader in px.
 * @param leaderHeight Height of the Callout leader in px.
 * @param minSize Minimum size the of the Callout shape.
 * @param calloutScreenCoordinate Represents the x,y coordinate of the Callout leader.
```

2024-05-15 21:43 UTC, sorenoid commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> + * [leaderHeight] Height of the Callout leader in px.
```suggestion
 * @param size The calculated size of the resulting content used to created the Path.
 * @param cornerRadius The corner radius of the rectangle shape in px.
 * @param leaderWidth Width of the Callout leader in px.
 * @param leaderHeight Height of the Callout leader in px.
```

2024-05-15 21:43 UTC, sorenoid commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +    properties: CalloutProperties = DefaultCalloutProperties,
I think you said this is under construction still? Consider making this just a variable in the Callout body until we are ready to promote it to public API. That way if we don't get to it, it won't be released as part of the API and this a breaking change to remove it or change it.

2024-05-15 21:43 UTC, sorenoid commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +public data class CalloutProperties(
Likewise consider making this internal or private for now.

2024-05-15 21:43 UTC, sorenoid commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +internal val DefaultCalloutProperties = CalloutProperties()
I suspect this capital `D` triggers a lint warning? As mentioned below, consider calling this within the scope of the Callout body until we are ready to release a public theming API for Callout.

2024-05-15 23:45 UTC, shubham7109 commented
@sorenoid Thanks for the feedback, I added in the changes. Ready for your review

2024-05-17 22:03 UTC, shubham7109 commented
Resolved merge conflicts, and is ready for review. 


@puneet-pdx Could you help ensure the [merge commit](https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/421/commits/2581be7bd9e62ff193581582b3161519b060ecdb) changes to resolve the conflicts look right to you.  I tested using an custom offset it seems to work as expected.

2024-05-17 23:22 UTC, eri9000 approved these changes
LGTM 👍🏼

2024-05-17 23:28 UTC, merged