`Forms` : View Attachments
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #422
Opened 2024-05-10 01:56 UTC by kaushikrw

2024-05-15 14:37 UTC, sorenoid requested changes
Looks good. I have a couple questions

2024-05-15 14:37 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/internal/components/attachment/AttachmentElementState.kt
> +    private val formAttachment: FormAttachment? = null
Why is this nullable?

2024-05-15 16:10 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/internal/components/attachment/AttachmentElementState.kt
> +    private val formAttachment: FormAttachment? = null
This is to enable compose previews for `AttachmentTile`. For the preview null can be passed while at runtime during state creation, this will be populated.

2024-05-16 18:03 UTC, sorenoid approved these changes

2024-05-16 18:12 UTC, merged