`Forms` : Add attachment fixes
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #425
Opened 2024-05-13 22:28 UTC by kaushikrw

### Summary of changes

2024-05-15 14:46 UTC, sorenoid requested changes
looks good, just one suggestion to simplify the mapping of FormAttachment to FormAttachmentState.

2024-05-15 14:46 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/internal/components/attachment/AttachmentElementState.kt
> +    var attachments by mutableStateOf(emptyMap<Int, FormAttachmentState>())
FormAttachments are unique, persistent, and implement equals and hashCode. You can key on them, and if that doesn't work there is likely a bug somewhere.
```suggestion
    var attachments by mutableStateOf(emptyMap<FormAttachment, FormAttachmentState>())
```

2024-05-15 16:23 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/internal/components/attachment/AttachmentElementState.kt
> +    var attachments by mutableStateOf(emptyMap<Int, FormAttachmentState>())
I believe this should work too, but it the adds a `FormAttachment` dependency to the `AttachmentFormElement`. This would mean previews cannot be generated with a list of attachments.

```
@Composable
AttachmentFormElement(
    ..
    attachments: Map<FormAttachment, FormAttachmentState>,
    ..
)

2024-05-16 18:04 UTC, sorenoid approved these changes

2024-05-16 21:02 UTC, merged