`Popup` attachment element
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #430
Opened 2024-05-15 21:22 UTC by sorenoid

support to display AttachmentsPopupElement in a Popup with
* gallery view of read only Popup attachments.
* support for loading attachments
* support for image, video, document and "other" content types.
* support for thumbnails on image attachments.
* encapsulated theming values

2024-05-17 20:33 UTC, puneet-pdx approved these changes
@sorenoid LGTM 👍🏽 . Could use some cleaning up of unnecessary newlines which I pointed out.

2024-05-17 20:33 UTC, puneet-pdx commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/element/attachment/AttachmentsElementDefaults.kt
> +
Unnecessary newlines here

2024-05-17 20:33 UTC, puneet-pdx commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/element/attachment/AttachmentsElementState.kt
> +
unnecessary newline

2024-05-17 20:33 UTC, puneet-pdx commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/element/attachment/AttachmentsPopupElement.kt
> +
could remove the newline here

2024-05-20 23:28 UTC, eri9000 requested changes
Good work 👍🏼 
A few suggestions...

2024-05-21 17:37 UTC, eri9000 approved these changes
LGTM 👍🏼

2024-05-22 00:10 UTC, merged