Add changes to show only one callout on the mapview
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #442
Opened 2024-05-23 00:31 UTC by puneet-pdx

- Add Callout implementation function as the member function of MapViewScope
- Abstract the callout parameters to a data class which are used as a property on MapViewScope
- Add public Callout composable function that calls the internal MapViewScope.Callout only for the first time
- Add call to reset MapViewScope.CalloutParameters in MapView to reset the callout parameters on screen rotation
- Move public Callout composable to the beginning of the file
- Add doc to public Callout composable that only one callout is supported

2024-05-23 19:07 UTC, sorenoid requested changes
some suggestions.

2024-05-23 19:07 UTC, sorenoid commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +        private fun GeoView.rotation(): Double = when (this) {
There are reasons to avoid member extension functions, as outlined [here](https://kt.academy/article/ek-member-extensions). Are there good reasons that this and the other extension functions should be members?

2024-05-23 19:07 UTC, sorenoid commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +        /**
Indentation is off from here to the end of the class.

2024-05-24 00:02 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +     * that contains the content lambda provided by the application. A thin border line is drawn around the entire Callout.
I have simplified the doc. Was having problems having the `@see` tag to lead to the public function so I have not added it.

2024-05-24 00:02 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +        private fun GeoView.rotation(): Double = when (this) {
updated

2024-05-24 00:02 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +        /**
updated

2024-05-24 19:03 UTC, sorenoid approved these changes
👍

2024-05-28 19:28 UTC, shubham7109 approved these changes
Looks good 👍

2024-05-28 19:28 UTC, shubham7109 commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +     * @param offset the offset in screen coordinates from the geographical location at which to place the callout
```suggestion
     * @param offset the offset in screen coordinates from the geographical location at which to place the Callout
```

2024-05-28 20:49 UTC, puneet-pdx commented
Thanks @sorenoid @shubham7109 . Merging..

2024-05-28 20:49 UTC, merged