Callout MicroApp
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #447
Opened 2024-05-29 01:32 UTC by shubham7109

2024-05-29 15:14 UTC, sorenoid requested changes

2024-05-29 15:14 UTC, sorenoid commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/MapView.kt
Please move this change into a separate PR where we can consider its merits in isolation.

2024-05-31 00:18 UTC, puneet-pdx approved these changes
LGTM

2024-05-31 23:26 UTC, sorenoid approved these changes
some comments that we discussed. happy to approve ahead of changes.

2024-05-31 23:26 UTC, sorenoid commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/TapLocationScreen.kt
> +    var offset by remember { mutableStateOf(Offset.Zero) }
as discussed these should be rememberSaveable'd

2024-06-03 16:33 UTC, puneet-pdx commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/TapLocationScreen.kt
> +    var offset by remember { mutableStateOf(Offset.Zero) }
Offset will require custom Saver implementation so I have just moved it to the viewModel. I have made the other two that are primitive types rememberSaveable.

2024-06-03 16:33 UTC, merged