`Popup:` Adds a file viewer for image attachments
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #455
Opened 2024-06-04 22:48 UTC by eri9000

2024-06-05 17:00 UTC, sorenoid requested changes
I have not run this yet, but have some suggestions that should be considered.

2024-06-06 00:32 UTC, eri9000 commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/fileviewer/FileViewer.kt
> +    AsyncImage(
I fixed the content scale by adding a modifier to fill max screen. Now i can see the smaller images fit the screen

2024-06-13 15:59 UTC, kaushikrw requested changes

2024-06-13 22:01 UTC, kaushikrw approved these changes
Looks good! Just some minor nitpicks that don't need a re-review.

2024-06-13 22:01 UTC, kaushikrw commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/ui/fileviewer/FileViewer.kt
>                          withContext(Dispatchers.Main) {
```suggestion
```
I believe the default would be `Dispatchers.Main` along with the above suggestion.

2024-06-17 20:26 UTC, sorenoid requested changes
overall looks great. Strings need to be added to resources, a few odds and ends but overall well done.

2024-06-17 20:26 UTC, sorenoid commented on toolkit/popup/src/main/AndroidManifest.xml
> +            android:authorities="${applicationId}.fileprovider"
This should be made a little more unique.

```suggestion
            android:authorities="${applicationId}.arcgis.popup.fileprovider"
```

2024-06-17 20:26 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/ui/fileviewer/ImaveViewer.kt
There's typo in the file name

2024-06-17 20:26 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/ui/fileviewer/ImaveViewer.kt
> +internal fun ImageViewer(path: String) {
Does ImageViewer do anything besides just wrap the call to AsyncImage. It doesn't seem necessary.

2024-06-17 20:26 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/ui/fileviewer/ViewableFile.kt
> +        "${context.applicationContext.applicationInfo.packageName}.fileprovider",
If changes in the manifest are made to make the authority more unique, this will need to change as well.
```suggestion
        "${context.applicationContext.applicationInfo.packageName}.arcgis.popup.fileprovider",
```

2024-06-17 20:26 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/ui/fileviewer/FileViewer.kt
> +                text = { Text("Share", color = MaterialTheme.colorScheme.onSurface) },
Share and Save strings need to be localized.

2024-06-17 20:26 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/ui/fileviewer/FileViewer.kt
> +                            Toast.makeText(context, "Save failed", Toast.LENGTH_SHORT).show()
localize here.

2024-06-17 20:26 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/ui/fileviewer/FileViewer.kt
> +                    Icon(Icons.Rounded.Save, contentDescription = "Save", tint = MaterialTheme.colorScheme.onSurface)
localize the content description here.

2024-06-17 20:26 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/ui/fileviewer/FileViewer.kt
> +                    Icon(Icons.Rounded.Share, contentDescription = "Share", tint = MaterialTheme.colorScheme.onSurface)
localize the content description here.

2024-06-17 20:26 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/ui/fileviewer/FileViewer.kt
> +            Icon(Icons.Rounded.MoreVert, contentDescription = "More", tint = MaterialTheme.colorScheme.onSurface)
localize content description here.

2024-06-17 20:26 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/ui/fileviewer/FileViewer.kt
> +                    is ViewableFileType.Other -> Text("Other")
these Strings need to be localized.

2024-06-17 20:26 UTC, sorenoid commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/element/attachment/AttachmentTile.kt
>                  // TODO open attachment viewer in `else` here
comment can be removed

2024-06-17 21:23 UTC, eri9000 commented on toolkit/popup/src/main/java/com/arcgismaps/toolkit/popup/internal/ui/fileviewer/FileViewer.kt
> +                    is ViewableFileType.Other -> Text("Other")
I have added these to the strings.xml but i didn't reference these here bc I am planning on replacing these with the actual composables

2024-06-18 17:04 UTC, sorenoid approved these changes

2024-06-18 17:08 UTC, merged