Add support for Callout that takes GeoElement and TapLocation
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #459
Opened 2024-06-07 23:14 UTC by puneet-pdx

Related to issue: # https://devtopia.esri.com/runtime/kotlin/issues/4001

### Description:
Adds Callout composable function that displays a callout at the calculated optimum point from given geoElement and tap location.

### Summary of changes:

- Add public composable Callout that takes Geoelement, tapPoint and content as parameters
- Add test case for displaying callout on a feature in the micro app

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link: https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/3/
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No - Micro app is added for adhoc testing

2024-06-11 15:26 UTC, shubham7109 requested changes
Changes look good, I added a few suggestion comments:

2024-06-11 18:31 UTC, puneet-pdx commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/FeatureScreen.kt
>  import androidx.compose.foundation.layout.Box
updated

2024-06-11 18:52 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +import com.arcgismaps.geometry.PointBuilder
updated

2024-06-11 19:22 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +         * @return LeaderPointOffset the offset needed to place the Callout
updated

2024-06-11 19:22 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> + *        This is useful if you are showing the callout for elements with symbology that does not rotate with the [GeoView]
updated

2024-06-11 19:22 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +     * @return LeaderLocation the [LeaderLocation]
updated

2024-06-11 19:22 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +     * @return LeaderLocation the [LeaderLocation]
updated

2024-06-11 19:24 UTC, puneet-pdx commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/MapViewModel.kt
> +    val arcGISMapWithFeatureLayer = ArcGISMap("http://www.arcgis.com/home/webmap/viewer.html?webmap=a58aafbd19994eb38f374e205d1b7b30")
Let's do this as a part of enhancing the micro app

2024-06-11 19:25 UTC, puneet-pdx commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/FeatureScreen.kt
> +                        Text("Tapped location: ${tapLocation?.x?.roundToInt()},${tapLocation?.y?.roundToInt()}")
let's do this as a part of the issue for enhancing the micro app

2024-06-11 19:31 UTC, puneet-pdx commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/FeatureScreen.kt
>              modifier = Modifier.fillMaxSize(),
I cannot repro this. Let's chat about it.

2024-06-11 19:32 UTC, puneet-pdx commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/FeatureScreen.kt
>  //- add switch to enable/disable animation
I plan to leave it in as a part of this PR and the micro app in not in the scope of this issue. Let's clean this against the issue to enhance the micro app

2024-06-11 20:31 UTC, shubham7109 commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> + *        This is useful if you are showing the callout for elements with symbology that does not rotate with the [GeoView]
I noticed the same issue on the doc for location point function: `public fun MapViewScope.Callout`. Sorry I missed this as it was not part of the PR diff.

2024-06-11 20:34 UTC, shubham7109 approved these changes
Thanks for addressing the comments, I agree to take some feedback from this PR and prioritize microapp enhancements separately. 

LGTM 👍

2024-06-14 21:38 UTC, eri9000 reviewed
Good work @puneet-pdx 
see my comments

2024-06-14 21:38 UTC, eri9000 commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +     * Along with that information and the tap location it calculates the fitting placement
```suggestion
     * Along with that information and the tap location, it calculates the fitting placement
```

2024-06-14 21:38 UTC, eri9000 commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
> +    if (!angle.equals(0.0f)) {
```suggestion
    if (angle != 0.0f) {
```

2024-06-17 16:19 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/Callout.kt
>      val location: Point? = null,
That guideline is for composable functions and modifier is the first optional parameter, which is consistent here.

2024-06-17 22:41 UTC, puneet-pdx commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/FeatureScreen.kt
> +    var nullTapLocation by rememberSaveable { mutableStateOf(false) }
@shubham7109 can you take these changes into account in your PR ?

2024-06-17 22:45 UTC, eri9000 approved these changes

2024-06-17 22:56 UTC, shubham7109 commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/FeatureScreen.kt
> +    var nullTapLocation by rememberSaveable { mutableStateOf(false) }
Sure, @eri9000 I suspect this will need some thought. We can address it in #468, as I have updated the UI to say "Use tapped location: ".

2024-06-21 21:21 UTC, puneet-pdx commented
Thanks @shubham7109 @eri9000. Merging..

2024-06-21 21:21 UTC, merged