Callout styling
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #503
Opened 2024-07-09 22:56 UTC by shubham7109

Related to issue: https://devtopia.esri.com/runtime/kotlin/issues/3937

### Description:
PR to add the `CalloutTheme.kt` and `DefaultThemeTokens.kt` to enable custom styling on the Callout. 

<details><summary>Test Code: </summary>

```kotlin

import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.DpSize
import androidx.compose.ui.unit.dp
import com.arcgismaps.toolkit.geoviewcompose.MapView
import com.arcgismaps.toolkit.geoviewcompose.theme.CalloutDefaults

@Composable
fun GraphicScreen(mapViewModel: MapViewModel) {

    val tappedPoint = mapViewModel.mapPoint.collectAsState().value
    val calloutTheme = CalloutDefaults.colorScheme(
        calloutColorsProperties = CalloutDefaults.colorProperties(
            backgroundColor = Color.LightGray,
            borderColor = Color.Red
        ),
        calloutShapeProperties = CalloutDefaults.shapeProperties(
            cornerRadius = 0.dp,
            leaderSize = DpSize(25.dp, 20.dp),
            borderWidth = 5.dp,
            calloutContentPadding = PaddingValues(25.dp),
            minSize = DpSize(100.dp, 100.dp)
        )
    )
    Scaffold { contentPadding ->
        MapView(
            modifier = Modifier.fillMaxSize().padding(contentPadding),
            arcGISMap = mapViewModel.arcGISMap,
            graphicsOverlays = remember { listOf(mapViewModel.tapLocationGraphicsOverlay) },
            onSingleTapConfirmed = mapViewModel::setMapPoint
        ) {
            if (tappedPoint != null) {
                Callout(
                    location = tappedPoint,
                    colorScheme = calloutTheme
                ) {
                    Text(text = "HELLO WORLD")
                }
            }
        }
    }
}
```

</details>

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-07-10 18:58 UTC, shubham7109 commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/TapLocationScreen.kt
> +                                    textColor = MaterialTheme.colorScheme.onBackground,
I had to update the microapp to be able to update the text color, since the HtmlText here is wrapped with an AndroidView.

2024-07-10 19:01 UTC, shubham7109 commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/GeoViewScope.kt
> +                CalloutTheme{
Is this really needed? I am able to see the MicroApp theme being applied with/without this `CalloutTheme`

2024-07-10 21:17 UTC, shubham7109 commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/theme/CalloutTheme.kt
> +    }
@sorenoid @kaushikrw 

I might reconsider this `colorScheme` to be independent of the Shape properties, I think it might be bit misleading for users to modify the Callout shape from the ColorScheme. 

Looking at the Compose's Button [source code](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material3/material3/src/commonMain/kotlin/androidx/compose/material3/Button.kt;l=112?q=file:androidx%2Fcompose%2Fmaterial3%2FButton.kt%20function:Button), they have a separate parameter for the shape and color. We can do something similar with Callout function parameters:

```kotlin
    @Composable
    public fun Callout(
        location: Point,
        modifier: Modifier = Modifier,
        offset: Offset = Offset.Zero,
        rotateOffsetWithGeoView: Boolean = false,
        colorScheme: CalloutColorScheme = CalloutDefaults.colorScheme(),
        shape: CalloutShape = CalloutDefaults.shape(),
        content: @Composable BoxScope.() -> Unit
    ) { ....
```

Would like any feedback if there would be concerns with this approach.

2024-07-11 16:21 UTC, sorenoid commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/theme/CalloutTheme.kt
> +    }
although I would call it `CalloutShapes` rather than `CalloutShape`, adnd `CalloutDefaults.shapes()

2024-07-11 22:41 UTC, shubham7109 commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/GeoViewScope.kt
> +                            )
Wrapped the callout Box to here with `with(LocalDensity..` (https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/503/commits/90c36532c7c12eacf846422db30076db161b434d)

2024-07-11 22:42 UTC, shubham7109 commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/theme/CalloutTheme.kt
> +public data class CalloutShapeProperties internal constructor(
Updated to: 
```kotlin
public fun Callout(
    geoElement: GeoElement,
    modifier: Modifier = Modifier,
    tapLocation: Point? = null,
    colorScheme: CalloutColors = CalloutDefaults.colors(),
    shape: CalloutShapes = CalloutDefaults.shapes(),
    content: @Composable BoxScope.() -> Unit
) {
```

2024-07-11 22:43 UTC, shubham7109 commented on microapps/MapViewCalloutApp/app/src/main/java/com/arcgismaps/toolkit/mapviewcalloutapp/screens/TapLocationScreen.kt
> +                                    textColor = MaterialTheme.colorScheme.onBackground,
Correct!

2024-07-11 22:54 UTC, shubham7109 commented
@sorenoid Thanks for the feedback, I've updated the PR with the chang requests and the description test code. Ready for your review.

2024-07-12 22:55 UTC, sorenoid approved these changes
👍

2024-07-13 22:19 UTC, kaushikrw requested changes
I think the `CalloutTheme` is not needed. I've added some context below..

2024-07-13 22:19 UTC, kaushikrw commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/theme/CalloutTheme.kt
> +public data class CalloutShapes internal constructor(
Missing doc for parameters. The doc should ideally define what each property corresponds to in the UI.

2024-07-13 22:19 UTC, kaushikrw commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/theme/CalloutTheme.kt
> +public data class CalloutColors internal constructor(
Missing doc for parameters.

2024-07-13 22:19 UTC, kaushikrw commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/theme/CalloutTheme.kt
> +    public fun colors(
Missing doc for parameters.

2024-07-13 22:19 UTC, kaushikrw commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/theme/CalloutTheme.kt
> +    public fun shapes(
Missing doc for parameters.

2024-07-13 22:19 UTC, kaushikrw commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/GeoViewScope.kt
> +        shape: CalloutShapes,
```suggestion
        shapes: CalloutShapes,
```

2024-07-13 22:19 UTC, kaushikrw commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/GeoViewScope.kt
> +        shape: CalloutShapes = CalloutDefaults.shapes(),
```suggestion
        shapes: CalloutShapes = CalloutDefaults.shapes(),
```

2024-07-13 22:19 UTC, kaushikrw commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/GeoViewScope.kt
> +        shape: CalloutShapes = CalloutDefaults.shapes(),
```suggestion
        shapes: CalloutShapes = CalloutDefaults.shapes(),
```

2024-07-13 22:19 UTC, kaushikrw commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/GeoViewScope.kt
> +        shape: CalloutShapes,
```suggestion
        shapes: CalloutShapes,
```

2024-07-13 22:19 UTC, kaushikrw commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/GeoViewScope.kt
> +                    }
If the `drawCalloutContainer` already accepts all these parameters then I don't see a need for the `CalloutTheme`. It is not being used at all. A theme and the use of composition local makes sense when the hierarchy is much more complex and deep. 

In this case, I think the `CalloutTheme` and their CompositionLocal's can be completely eliminated and you could simply pass the `CalloutShapes` and `CalloutColors` down to this modifier.

2024-07-15 19:00 UTC, shubham7109 commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/GeoViewScope.kt
> +                    }
Thanks @kaushikrw, this helps clarify the usage of the theme.

2024-07-15 19:04 UTC, shubham7109 commented
@kaushikrw Ready for your re-review. I added the missing doc, removed the use of CalloutTheme & composition local, and changed the shape param to "shapes".

2024-07-15 21:09 UTC, kaushikrw commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/GeoViewScope.kt
> +        shape: CalloutShapes,
Missed this..

2024-07-15 21:39 UTC, shubham7109 commented
Ah sorry, thanks for pointing it out. Ready for your review @kaushikrw

2024-07-15 21:40 UTC, kaushikrw approved these changes
LGTM!

2024-07-15 21:41 UTC, merged