Initial Implementation of UN Trace tool
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #544
Opened 2024-08-21 23:25 UTC by eri9000

### Description:
- Adds initial implementation of Trace Tool
- The UI will display the available Trace Types in the Utility Network
- Adding points does not work and uses dummy values. 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-08-22 20:20 UTC, puneet-pdx reviewed
@eri9000 some comments. We can discuss the comments regarding the UI options.

2024-08-22 20:20 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceConfiguration.kt
> +    ExpandableCard(title = stringResource(id = R.string.trace_types), toggleable = true) {
I don't think the ExapandableCard is a good fit here. We will get better functionality here with a dropdownlist. We can discuss if you like.

2024-08-22 20:20 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceConfiguration.kt
> +internal fun TraceConfiguration(traceTypes: List<SelectableItem>, onPerformTrace: () -> Unit) {
This composable should be called something like `NewTraceConfigurationOptions`, as it comprises of all the UI components that help user select configuration for a new trace.

2024-08-22 20:20 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceConfiguration.kt
> +private fun TraceTypes(utilityTraces: List<SelectableItem>, onTraceSelected: (Int) -> Unit) {
```suggestion
private fun TraceTypeSelector(utilityTraces: List<SelectableItem>, onTraceSelected: (Int) -> Unit) {
```

2024-08-22 20:20 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceConfiguration.kt
> +private fun AddTracePoint() {
```suggestion
private fun StartingPointsEditor() {
```

2024-08-22 20:20 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceConfiguration.kt
> + * A composable used to run a trace on a [UtilityNetwork].
```suggestion
 * A composable used to specify input options and run a trace on a [UtilityNetwork].
```

2024-08-22 20:20 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceConfiguration.kt
> + * This composable is used to select the trace configuration and starting points for the trace.
```suggestion
 * This composable provides options to the user to be able to select the trace configuration and add starting points for performing the trace.
```

2024-08-22 20:20 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceConfiguration.kt
> + * A composable used to display the trace types.
```suggestion
 * A composable to display the available trace types and help user make a selection.
```

2024-08-22 23:14 UTC, puneet-pdx approved these changes

2024-08-22 23:55 UTC, sorenoid requested changes
Looks good. Just a couple things mostly around the new shared module:
* probably want to remove the example tests
* should add the new module to the list of modules to exclude from test reporting in the top level build.gradle.

2024-08-22 23:55 UTC, sorenoid commented on toolkit/sharedlib/src/androidTest/java/com/esri/sharedlib/ExampleInstrumentedTest.kt
Let's just remove the tests if there are no plans to write any.

2024-08-22 23:55 UTC, sorenoid commented on toolkit/sharedlib/src/test/java/com/esri/sharedlib/ExampleUnitTest.kt
lets remove the tests if there are no plans to write them.

2024-08-22 23:55 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/Trace.kt
> +    LaunchedEffect(key1 = null) {
```suggestion
val availableTraceConfigurations = remember(utilityNetwork) { 
    mutableStateListOf<UtilityNamedTraceConfiguration>() 
}

LaunchedEffect(key1 = utilityNetwork) {
```

2024-08-22 23:55 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/Trace.kt
> +    LaunchedEffect(key1 = null) {
two things here

* the list of available configurations is dependent on the UtilityNetwork, so both the remember and the launched effect should key on it. I know this is all going to change but this may well remain and should be changed.
* I changed the the name of the variable because it seemed a bit misleading.

2024-08-22 23:55 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptions.kt
> +internal fun TraceOptions(traceTypes: List<SelectableItem>, onPerformTrace: () -> Unit) {
Remind me to add these internal composable to the list of API that should be ignored. (it's a bug in compose, or was that public "composable singletons" are generated for internal composables...). I'll do it when we settle on naming!

2024-08-24 00:58 UTC, sorenoid approved these changes

2024-08-26 16:01 UTC, merged