Change Design of Dialog Authenticator Catalog
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #547
Opened 2024-08-26 23:28 UTC by NourdotSiwar

Related to issue:
#[3905](https://devtopia.esri.com/runtime/kotlin/issues/3905)
#[2551](https://devtopia.esri.com/Apps/apps-android-200/issues/2551)

### Description:
Request to change the design of Authenticator Dialog in order to solve the related issues.

### Summary of changes:
Changed Basic Dialog to Alert Dialog
Added supporting text and title
Changed text to reflect more against [Design Conventions](https://app.abstract.com/share/f9cb669c-de3e-437d-8d34-127651314c5f)
### Pre-merge Checklist
a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
 link:

2024-09-03 19:18 UTC, eri9000 requested changes
Good progress, 
see my suggestions.

2024-09-03 19:18 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +        val hostname = uri.host
I don't think this is needed, we were previously using `url`

2024-09-03 19:18 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                        text = "You need to sign in to access the following: $hostname",
can we use the older resource: `R.string.username_password_login_message`

2024-09-03 19:18 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +            modifier = Modifier.fillMaxWidth(0.92f),
how was this calculated?

2024-09-03 19:18 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                    Text(text = "Sign In")
```suggestion
                    Text(stringResource(id = R.string.login))
```

2024-09-03 19:18 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +            onDismissRequest = authenticatorState::dismissAll,
should this also cancel the challenge?

2024-09-03 19:18 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/ServerTrustAuthenticator.kt
> +                        text = "The certificate provided by $hostname is not signed by a trusted authority.",
you can use the string resource instead: `R.string.server_trust_message`

2024-09-03 19:18 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                Text(text = "Authentication Required")
This needs to be a string resource under `res -> values -> strings -> strings.xml`

2024-09-03 22:02 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +        val hostname = uri.host
actually, this would fit better in `UsernamePasswordChallenge`.
you can add a lazy property `hostname` that does this.

2024-09-04 00:44 UTC, nickneilsonblack commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/ServerTrustAuthenticator.kt
> +                Column(
Does this content need to be in a Column? there doesn't seem to be any other child elements

2024-09-04 01:04 UTC, nickneilsonblack commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                Text(text = "Authentication Required")
Is it possible to pass the title text in? In Field Maps we'd like the title to be `Secured Layer`

2024-09-04 01:07 UTC, nickneilsonblack commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                    verticalArrangement = Arrangement.SpaceBetween,
The vertical spacing of the username and password field look a bit tight. Would it be possible to use `Arrangement.spacedBy(16.dp)` instead to conform with MD3 guidelines?

2024-09-04 01:10 UTC, nickneilsonblack commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                        text = "You need to sign in to access the following: $hostname",
Is it possible to pass in this message? In Field Maps we'd like it to say:
`You need to sign in to access [service name]`

2024-09-04 01:14 UTC, nickneilsonblack commented
Agree- this looks like great progress- thanks @NourdotSiwar 

For the **Screenshot on Pixel 5** do you know why the alignment of the text fields looks off on the leading edge and there's no scrim behind the dialog?

<img width="391" alt="image" src="https://github.com/user-attachments/assets/f641fee6-9503-4d6c-85c2-894b643ca218">

2024-09-04 03:22 UTC, NourdotSiwar commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +            modifier = Modifier.fillMaxWidth(0.92f),
This was taken from [stackoverflow](https://stackoverflow.com/questions/74519216/compose-alertdialog-always-takes-full-width-on-samsung) to fix the Compose bug for Samsung taking up full screen with Dialog components

2024-09-04 03:26 UTC, NourdotSiwar commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                    Text(text = "Sign In")
Ah- The reason I changed this in particular was in order to align with what @mikewilburn suggested how "login" is a noun vs a verb phrase. Also see: [Terminology Guidelines](https://docresources.esri.com/doc-guides/en/style-guide/terminology-guidelines.html)

2024-09-04 03:33 UTC, NourdotSiwar commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/ServerTrustAuthenticator.kt
> +                Column(
Thank you for pointing this out! You're right, it does not seem to have any effect

2024-09-04 03:40 UTC, NourdotSiwar commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                    verticalArrangement = Arrangement.SpaceBetween,
Yeah sure thing!
This is what it would look like though: 
![Uploading Screenshot 2024-09-03 at 8.39.26 PM.png…]()

2024-09-04 03:42 UTC, NourdotSiwar commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                    verticalArrangement = Arrangement.SpaceBetween,
Yeah sure thing!
This is what it would look like on Pixel 5: 
<img width="250" alt="Screenshot 2024-09-03 at 8 41 24 PM" src="https://github.com/user-attachments/assets/308e867e-21fd-4d32-b379-6dee661c0a0b">

2024-09-04 03:43 UTC, NourdotSiwar commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                    verticalArrangement = Arrangement.SpaceBetween,
Regarding your other comment about the textfields looking off on the leading edge, that alignment has been fixed and now everything is aligned to left. 

Regarding the scrim, it looks like this is only a Pixel5 situation where the background does not darken, but only Samsung and other devices, it darkens.

2024-09-04 16:45 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                    Text(text = "Sign In")
Gotcha. In that case, could you also make it a string resource?

2024-09-04 21:50 UTC, NourdotSiwar commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticator.kt
> +                Text(text = "Authentication Required")
Due to time limit on my end, as I will be ending my internship this week, the team has decided to move any out of scope things to a different [issue](https://zentopia.esri.com/workspaces/us-workspace-603d242421bc3a4ab636a2db/issues/gh/runtime/kotlin/4576), which will include passing the title text in

2024-09-04 22:06 UTC, NourdotSiwar commented
Continuing issue to refactor authenticator: https://zentopia.esri.com/workspaces/us-workspace-603d242421bc3a4ab636a2db/issues/gh/runtime/kotlin/4576

2024-09-04 23:08 UTC, eri9000 requested changes
@NourdotSiwar 
Good progress,
some more suggestions.

2024-09-04 23:08 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordChallenge.kt
We don't want this to be nullable, we can guard it as such: 
```suggestion
    public val hostname: String by lazy {
        Uri.parse(url).host ?: url
    }
```

2024-09-04 23:08 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/UsernamePasswordAuthenticatorImpl.kt
> +        val hostName = usernamePasswordChallenge.hostname!!
No need for this: 
```suggestion
        val hostName = usernamePasswordChallenge.hostname
```

2024-09-04 23:10 UTC, eri9000 commented on toolkit/authentication/src/main/java/com/arcgismaps/toolkit/authentication/Authenticator.kt
> +                onPendingOAuthUserSignIn = onPendingOAuthUserSignIn,
The modifier needs to be passed to the `AuthenticatorDelegate`
```suggestion
                modifier = modifier,
                onPendingOAuthUserSignIn = onPendingOAuthUserSignIn,
```

2024-09-05 16:33 UTC, eri9000 requested changes
Good work @NourdotSiwar 👍🏼 
Some more suggestions.

2024-09-05 18:08 UTC, eri9000 approved these changes
Good work @NourdotSiwar 
LGTM 👍🏼

2024-09-05 22:41 UTC, sorenoid approved these changes
LGTM. Seems like a good candidate for exposing a public theme API for text style and spacing, keybpard types, etc. We can return to that and maybe extract the material3 tokens used here. Looks great!

2024-09-06 17:17 UTC, merged