add theming to ExpandableCard
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #548
Opened 2024-08-28 01:26 UTC by sorenoid

Related to issue: #4518

### Description:

add theming composition locals to the shared ExpandableCard composable component so that theming on behalf of one consumer of the component don't affect other consumers of the component.

### Summary of changes:

- composition locals for typography, shapes, and color
- ExpandableCardTheme composable
- default tokens for use in previews

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [x] link: https://runtime-kotlin.esri.com/view/vTest/job/vtest/job/toolkit/71/
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-08-28 18:41 UTC, eri9000 requested changes
Some suggestions

2024-08-28 18:41 UTC, eri9000 commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/DefaultThemeTokens.kt
> +
Just for consistency
```suggestion

    /**
     * The default values provided are hardcoded based on the material 3 shapes.
     * See [androidx.compose.material3.Shapes]
     */
```

2024-08-28 18:41 UTC, eri9000 commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardDefaults.kt
> +    private fun bodyStyleTypography(): TextStyle = MaterialTheme.typography.bodyMedium
can we use both of these directly?

2024-08-28 18:41 UTC, eri9000 commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardDefaults.kt
> +    private fun borderThickness(): Dp = 1.dp
can we use these directly also?

2024-08-28 18:41 UTC, eri9000 commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardTheme.kt
> + * on the current [MaterialTheme].
is this needed?

2024-08-28 18:41 UTC, eri9000 commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardTheme.kt
> + * @param content The content to which the theme should be applied.
```suggestion
 * @param colorScheme An [ExpandableCardColorScheme] to use for this compose hierarchy. Default is [ExpandableCardDefaults.colorScheme].
 * @param typography An [ExpandableCardTypography] to use for this compose hierarchy. Default is [ExpandableCardDefaults.typography].
 * @param shapes An [ExpandableCardShapes] to use for this compose hierarchy. Default is [ExpandableCardDefaults.shapes].
 * @param content The content to which the theme should be applied.
```

2024-08-28 18:41 UTC, eri9000 commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardTheme.kt
> +fun ExpandableCardTheme(
```suggestion
internal fun ExpandableCardTheme(
```

2024-08-30 16:35 UTC, sorenoid commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardTheme.kt
> +fun ExpandableCardTheme(
this breaks compilation.

2024-08-30 18:39 UTC, kaushikrw requested changes

2024-08-30 18:39 UTC, kaushikrw commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardTheme.kt
> +    val borderThickness: Dp
I think the `padding` and `borderThickness` can be parameters on the `ExpandableCard` composable. They feel a little out of place here.

2024-08-30 18:39 UTC, kaushikrw commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardTheme.kt
> +    val galleryContainerColor: Color,
```suggestion
    val galleryContainerColor: Color,
```
I don't see this property being used in `ExpandableCard`. Am I missing something?

2024-08-30 18:39 UTC, kaushikrw commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardTheme.kt
> +    val bodyStyle: TextStyle
```suggestion
    val headerStyle: TextStyle,
    val bodyStyle: TextStyle
```
Similarly, these are not utilized in `ExpandableCard`.

2024-08-30 18:39 UTC, kaushikrw commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptions.kt
> +        ExpandableCardTheme(
I believe it might be more effective to consider making the `ExpandableCardTheme` internal and allowing the `ExpandableCard` to accept colors, typography, and shapes as parameters. The theme and the inner workings then become internal to the component which might be more ideal than user code having to declare the theme.

[Example](https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/blob/0e54056a49f3b89967dcbdd7ebb69ed0ee97a5ac/toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/FeatureForm.kt#L129)

2024-08-30 18:39 UTC, kaushikrw commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardDefaults.kt
> +
```suggestion
```

2024-08-30 18:39 UTC, kaushikrw commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/ExpandableCard.kt
> +    colors: ExpandableCardColorScheme,
```suggestion
    colors: ExpandableCardColorScheme,
    typography: ExpandableCardTypography
```
This would need to also accept the typography.

2024-09-02 17:19 UTC, sorenoid commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardTheme.kt
> +    val borderThickness: Dp
I agree on the padding which can be passed via modifier, but think that borderThickness pertains to the component itself and is on an equal footing with containerShape.

2024-09-03 17:06 UTC, merged