UN trace tool config UI
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #552
Opened 2024-09-03 18:25 UTC by sorenoid

Related to issue: https://devtopia.esri.com/runtime/kotlin/issues/4518

### Description:

Solidify Trace Configuration and Starting Point editor UI
* tighten rows of Trace Configuration card
* use TextField rather than Chip for named trace configurations
* move add new starting point button into the ExpandableCard header
* starting point row composable which allows for conifmation of deleting a starting point with no dialog.

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [x] link: https://runtime-kotlin.esri.com/view/vTest/job/vtest/job/toolkit/73/
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-09-04 00:11 UTC, puneet-pdx reviewed
@sorenoid just a question.

2024-09-04 00:11 UTC, puneet-pdx commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/gestures/AnchoredDraggable.kt
> + * This is a copy of androidx.compose.foundation.gestures.AnchoredDraggable until that API is
@sorenoid are we Ok brining the classes marked as experimentalApi in Compose into our shared libs for usage ? Is that decided as the way forward for situations like this ? Do we need to discuss this in the team ?

2024-09-04 00:23 UTC, sorenoid commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/gestures/AnchoredDraggable.kt
> + * This is a copy of androidx.compose.foundation.gestures.AnchoredDraggable until that API is
@puneet-pdx The classes aren't marked as experimental in our shared libs.

2024-09-04 00:25 UTC, puneet-pdx commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/gestures/AnchoredDraggable.kt
> + * This is a copy of androidx.compose.foundation.gestures.AnchoredDraggable until that API is
@sorenoid yes I saw that, I was just wondering if this work around for experimental API is OK.

2024-09-04 00:31 UTC, sorenoid commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/gestures/AnchoredDraggable.kt
> + * This is a copy of androidx.compose.foundation.gestures.AnchoredDraggable until that API is
as far as bringing code into our repo that is "forked" from material3, the goal is to prevent breaking changes when we rev our version of the compose BOM, as has happened in the past and which we solved by bringing material 3 code into our codebase just like this.

2024-09-04 00:32 UTC, puneet-pdx approved these changes

2024-09-04 15:35 UTC, sorenoid commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/gestures/AnchoredDraggable.kt
> + * This is a copy of androidx.compose.foundation.gestures.AnchoredDraggable until that API is
@puneet-pdx We discussed this a bit last week while you were out. If you have reservations we should talk about it today. But in any event, I'd ask that we review it for lower level shortcomings as is, and create follow on issues to make higher level changes.

2024-09-04 21:43 UTC, eri9000 requested changes
Good initial work,
see my suggestions

2024-09-04 21:43 UTC, eri9000 commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/theme/ExpandableCardDefaults.kt
> +        readOnlyTextColor: Color = Color.Unspecified,
I don't think we need this. 
It seems this will only apply to the TraceOptions screen so we might be able to do this there.

2024-09-04 21:43 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptions.kt
> +private fun StartingPointRow(
I noticed that I have to tap on the trash Icon to make it deletable, would it be hard to make it just slide without tapping the trash icon first?

2024-09-04 21:43 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptions.kt
>              ElevatedButton(
can this me centered?

2024-09-04 21:52 UTC, eri9000 commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/ExpandableCard.kt
>      padding: Dp,
somehow this padding is not getting applied. 
see what we have in V.next vs here: 
![Screenshot 2024-09-04 at 14 51 35](https://github.com/user-attachments/assets/2f64c13a-457a-412f-9926-ff16a043ec27)
![Screenshot 2024-09-04 at 14 51 18](https://github.com/user-attachments/assets/2cb8457a-1e6c-45b7-9a06-f738f89a1a5a)

2024-09-05 19:39 UTC, sorenoid commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/modifier/Modifier.kt
> +fun Modifier.applyIf(condition: Boolean, then: Modifier.() -> Modifier): Modifier =
that isn't logically equivalent which is why it is in an extension method. Your suggestion would only work if the suggestion is the first modifier applied, which would look like this

```kotlin
Modifier
    .then(if(expandable) Modifier.clickable { onClick() } else Modifier)
    .fillMaxWidth()
    background(colors.headerBackgroundColor)
```

which is awkward. I think the extension is appropriate to avoid this.

 If it is not the first modifier applied, it would lose all previous modifiers applied to the current modifier, in the usage we have it would lose `fillMaxWidth()`.

2024-09-05 19:46 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptions.kt
> +private fun StartingPointRow(
It would be a bit of work, but doable. I was trying to prevent accidental deletions, equivalent to an "are you sure" dialog but without a dialog. The swipe is fairly bullet proof though.

As long as it is stable and not hideous, do you mind if we let Rama play with it and gather up feedback like this? I am sure there will be more feedback...

2024-09-05 20:06 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptions.kt
> +private fun ReadOnlyTextField(
I moved this into its own file because there will be editable text in the advanced options which can go in there as well. Text fields take a lot of attention to detail and it is worth isolating them.

2024-09-05 20:07 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptions.kt
> +private fun ReadOnlyTextField(
I also changed the styling of the text.

2024-09-05 21:52 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptions.kt
>              ElevatedButton(
Yes, I think there is more work to do to move this button out of the header so it is always visible but for now let's center it and let Rama evaluate it.

2024-09-05 22:43 UTC, eri9000 approved these changes
LGMT 👍🏼

2024-09-05 22:43 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/Text.kt
might be better to rename file to `ReadOnlyTextField`?

2024-09-05 22:43 UTC, eri9000 commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/ExpandableCard.kt
> +                    text = "the description",
spacing if off here

2024-09-05 22:43 UTC, eri9000 commented on toolkit/sharedlib/src/main/java/com/arcgismaps/toolkit/ui/expandablecard/ExpandableCard.kt
> +                        //modifier = Modifier.fillMaxWidth(),
are these comment out lines needed?

2024-09-05 22:43 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptions.kt
> +                println("adding row for ${it.name}")
i don't think we need this

2024-09-05 23:38 UTC, merged