Upgrade kotlin and compose compiler plugin version
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #555
Opened 2024-09-05 18:58 UTC by puneet-pdx

Related to issue: # https://devtopia.esri.com/runtime/kotlin/issues/4551

### Description:

With the upgrade to the compose compiler to version 2.0 the FloorFilter has started crashing.

### Summary of changes:

- Upgrading the version to the latest 2.0.20 fixes the issue

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-09-05 19:29 UTC, sorenoid requested changes
this PR shold target v,next no?

2024-09-05 21:11 UTC, puneet-pdx commented
@sorenoid yes, I have updated it.

2024-09-06 15:21 UTC, sorenoid approved these changes
👍

2024-09-06 16:40 UTC, eri9000 approved these changes

2024-09-06 16:41 UTC, merged