advanced options ui
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #557
Opened 2024-09-06 00:20 UTC by sorenoid

Related to issue: # https://devtopia.esri.com/runtime/kotlin/issues/4488

### Description:

Adds UI for advanced options
* configurable for displaying only the color picker, as needed in the trace results screen (future)
* has name editor, color picker, and zoom to result switch.
* is collapsed by default (undisclosed)

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [x] link: https://runtime-kotlin.esri.com/view/vTest/job/vtest/job/toolkit/
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-09-06 18:41 UTC, puneet-pdx approved these changes
@sorenoid few minor comments. Won't hold the PR for them.

2024-09-06 18:41 UTC, puneet-pdx commented on toolkit/utilitynetworks/build.gradle.kts
> -    // If this were not an android project, we would just write `explicitApi()` in the Kotlin scope.
we should keep this doc around and just update the 'kotlinOptions: KotlinJvmOptions' to use the compilerOptions DSL

2024-09-06 18:41 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptions.kt
> +
unnecessary newline

2024-09-09 20:13 UTC, eri9000 requested changes
Good work @sorenoid

2024-09-09 20:13 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceColors.kt
> +    internal fun nextColor(): Color {
Doc doesn't seem to make sense here, better to add a TODO in "Trace Options" where this should be used. 
```suggestion
    /**
     * Returns the next color in the sequence.
     *
     * @since 200.6.0
     */
    @Suppress("unused")
    internal fun nextColor(): Color {
```

2024-09-10 19:51 UTC, eri9000 approved these changes
Good work 👍🏼

2024-09-10 19:55 UTC, merged