UN Trace Tool: Adds navigation and AddStartingPoingScreen
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #560
Opened 2024-09-06 22:22 UTC by eri9000

### Description:
- Adds compose navigation 
   - Adds NavHost
   - Adds Nav graph
- Adds AddStartingPointScreen 
   - Adds callbacks to start/stop "Add starting point" mode
   - Gives the user the ability to listen for mode changes.
   - This screen will display a cancel button to cancel the "Add starting point" mode
### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-09-09 19:50 UTC, sorenoid requested changes
Hey Erick, some things to consider. Looks good overall, just an idea to encapsulate mode changing logic

2024-09-09 19:50 UTC, sorenoid commented on microapps/UtilityNetworkTraceApp/app/src/main/java/com/arcgismaps/toolkit/utilitynetworktraceapp/screens/MainScreen.kt
> +                    }
The logic having to do with the mode change is a bit spread out in a couple places. I suggest encapsulating it in the state object, so it can be run when the mode actually changes. This lambda should be a mutable property on the state object, that can be set here so it can interact with the scaffoldState, but run when the mode changes in the state object's `updateAddPointMode` function.

2024-09-09 19:50 UTC, sorenoid commented on microapps/UtilityNetworkTraceApp/app/src/main/java/com/arcgismaps/toolkit/utilitynetworktraceapp/screens/MainScreen.kt
> +                    }
in addition, this only seems to hide the sheet the first time I add a point. which seems to be fixed if I make the suggested changed above.

2024-09-09 19:50 UTC, sorenoid commented on microapps/UtilityNetworkTraceApp/app/src/main/java/com/arcgismaps/toolkit/utilitynetworktraceapp/screens/MainScreen.kt
> +                    }
and lastly, related to the app logic, I cannot see the cancel button when the sheet is `partialExpand`. I believe this is a configurable percentage property somewhere in BottomSheetScaffold?

2024-09-09 19:50 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +        _addStartingPointMode.value = status
fwiw with the suggested addition of a lambda property `onAddStartingPointModeChanged`, the lambda should be called here when the mode changes.

2024-09-09 19:50 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/AddStartingPointScreen.kt
> +                onPointSelected()
suggested name change.

```suggestion
                onPointSelectionStopped()
```

2024-09-09 20:33 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +public sealed class AddStartingPointMode {
we discussed that but we think this makes it more readable and descriptive. Also, if we want to add more states later we could do it here easier.

2024-09-09 21:18 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +        }
@sorenoid this guard was added so that when the map is tapped during any other interaction, the identify is not kicked off.
We only want to identify when we are in "AddStartingPoint" mode

2024-09-10 00:11 UTC, eri9000 commented on gradle/libs.versions.toml
✅ Did some ad-hock testing and kicked of a test job

2024-09-10 19:32 UTC, sorenoid approved these changes
nice work

2024-09-11 18:59 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptions.kt
> +internal fun TraceOptions(
Should be renamed to `TraceOptionsScreen` to keep the naming consistent with `AddStartingPointScreen`

2024-09-11 18:59 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceNavigation.kt
> +internal sealed interface TraceRoute {
This could be simpler if it was an enum,

```Kotlin
internal enum class TraceRoute {
    TraceOptions,
    TraceResults,
    AddStartingPoint
} 
```

2024-09-11 18:59 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceNavigation.kt
> +        composable(TraceOptions.route) {
with changing TraceOptions to an enum, these calls will change to 
```Kotlin
navController.navigate(TraceRoute.TraceResults.name)
```

2024-09-11 22:11 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceNavigation.kt
> +        composable(TraceOptions.route) {
good call, i have made it an enum class

2024-09-11 22:41 UTC, puneet-pdx approved these changes
@eri9000 LGTM

2024-09-11 23:24 UTC, merged