Changes to make identify work
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #569
Opened 2024-09-12 20:20 UTC by puneet-pdx

Related to issue: # https://devtopia.esri.com/runtime/kotlin/issues/4584

### Description:

Added changes to make Identify work

### Summary of changes:

- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-09-12 22:40 UTC, sorenoid requested changes
nice improvement. One suggestion to consider.

2024-09-12 22:40 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    private var screenPoint: ScreenCoordinate? = null
It doesn't seem like either of these are needed as properties if both are passed from `addStartingPoint` to the `identify` method? 

If there is a reason to keep them, consider not having one as lateinit and the other as nullable. I would consider a computed getter on `screenPoint` to derive its value from the current value of `tapPoint` as follows

```kotlin
private var tapPoint: Point? = null
private val screenPoint: ScreenCoordinate
    get() = tapPoint?.let { mapViewProxy.locationToScreen(it) } ?: throw IllegalStateException("tapPoint cannot be null")
```

2024-09-12 22:40 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptionsScreen.kt
> +            Button(onClick = { onPerformTraceButtonClicked() }) {
this is a nice improvement 👍 .

2024-09-12 23:28 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    private var screenPoint: ScreenCoordinate? = null
yep, not needed as properties. Updated

2024-09-12 23:41 UTC, sorenoid approved these changes
👍

2024-09-16 18:45 UTC, eri9000 approved these changes
👍🏼

2024-09-16 18:45 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
>       *
doc needs to be updated

2024-09-16 18:45 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptionsScreen.kt
> +                    .padding(3.dp)
```suggestion
                    .padding(10.dp)
```
```suggestion
                    .padding(3.dp)
```

2024-09-16 21:09 UTC, merged