Adds Trace Result screen
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #572
Opened 2024-09-16 16:27 UTC by eri9000

### Description:
- Adds trace result screen with Function results

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-09-16 19:12 UTC, puneet-pdx approved these changes
@eri9000 Changes look good. I guess we will plug up the values with the other issue in the sprint backlog 👍🏽

2024-09-17 18:13 UTC, sorenoid requested changes
looks great. I have a couple of suggestions

2024-09-17 18:13 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceNavigation.kt
> +                    coroutineScope.launch {
can remove todo now.

2024-09-17 18:13 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +            DropdownMenu(
Can you please match the style of the ColorPicker DropdownMenu? I think some rounding is better, but higher priority is that the menus are styled consistently.

2024-09-17 18:13 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +internal data class TraceResults(val traceName: String, val functionResults: List<FunctionResult>)
to aid smart recomposition

```suggestion
@Immutable
internal data class TraceResults(val traceName: String, val functionResults: List<FunctionResult>)
```

2024-09-17 18:13 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +internal data class FunctionResult(val name: String, val value: String, val functionType: String)
to aid smart recomposition

```suggestion
@Immutable
internal data class FunctionResult(val name: String, val value: String, val functionType: String)
```

2024-09-17 22:36 UTC, sorenoid approved these changes

2024-09-17 23:19 UTC, merged