Changes to enable/disable Trace button
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #588
Opened 2024-09-24 18:47 UTC by puneet-pdx

Related to issue: #

### Description:

Enable Trace button only if a TraceConfiguration and starting points are available

### Summary of changes:

- Add `isTraceReady` state and use it to enable/disable the trace button

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link: https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/113/
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-09-24 23:30 UTC, sorenoid requested changes
some suggestions

2024-09-24 23:30 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    internal val isTraceReady = derivedStateOf {
this doesn't seem right. derivedStateOf is evaluated at the end of the re/composition. It is expensive and should be used when the state is changing more often than we want the UI to change. That isn't the case here.

2024-09-24 23:47 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptionsScreen.kt
> +            Button(onClick = { onPerformTraceButtonClicked() }, enabled = isTraceReady) {
Good catch!

2024-09-25 15:44 UTC, sorenoid approved these changes
👍

2024-09-25 15:54 UTC, merged