`Forms` : Barcode support
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #593
Opened 2024-09-27 20:43 UTC by kaushikrw

Related to issue: #

### Description:

### Summary of changes:

- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-10-08 00:25 UTC, sorenoid requested changes
Looks pretty good. I haven't run it yet. I have a couple questions until I can run it tomorrow..

2024-10-08 00:25 UTC, sorenoid commented on toolkit/featureforms/src/main/res/values/strings.xml
> +    <string name="barcode_permission_denied">Camera permissions are required to scan barcodes. Please enable camera permissions in your device settings.</string>
Shouldnt the permission be in the FeatureForms manifest? I understand that our library components dont usually handle requesting permissions, but if the client app doesn't have it in the app manifest, wont it not be possible to enable the permission at all in the app?

2024-10-09 19:26 UTC, sorenoid approved these changes

2024-10-09 19:50 UTC, kaushikrw commented
Thanks @sorenoid.

2024-10-09 19:50 UTC, merged