Add option to navigate to new trace from resultscreen
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #597
Opened 2024-09-30 20:54 UTC by puneet-pdx

Related to issue: # https://devtopia.esri.com/runtime/kotlin/issues/4492

### Description:

adds functionality to go from `Resultscreen` to `newTrace` and from `newTrace` back to `Resultscreen` if results are available

### Summary of changes:

- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link: https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/120/
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-10-01 17:41 UTC, puneet-pdx commented
### PR to review: https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/597

2024-10-02 21:17 UTC, sorenoid requested changes
Looks good, I have some suggestions.

2024-10-02 21:17 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptionsScreen.kt
> +                },
```suggestion
            Tab(
                selected = index == selectedTabIndex,
                onClick = {
                    selectedTabIndex = index
                    if (index == 1) {
                        onBackToResults()
                    }
                },
```

2024-10-02 21:17 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +@Composable
same advice as above.  Also, it seems like the internal`TabRow` could be reused in both results and trace options by passing in the lambda, tabItems, and selected index.

2024-10-03 00:50 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +        _currentTraceName.value = "${config.name} ${(_completedTraces.count { it.configuration.name == config.name } + 1)}"
as per our discussion this is working as expected.

2024-10-04 17:33 UTC, sorenoid requested changes
Looking good, I have a couple more questions/suggestions.

2024-10-04 17:33 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/internal/util/TabRow.kt
> +    androidx.compose.material3.TabRow(selectedTabIndex = selectedTabIndex) {
why is this fully qualified? It is because this function has the same name? If that is the case I would change the name of this function.

2024-10-04 17:33 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/internal/util/TabRow.kt
> +    tabItems: List<String> = listOf(stringResource(R.string.new_trace), stringResource(R.string.results)),
this doesn't seem to need to be a parameter. If you want to keep it a parameter, I suggest moving it to the end of the parameter list so that `selectedIndex` doesn't have to be explicitly named when calling this function.

2024-10-04 18:05 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/internal/util/TabRow.kt
> +    androidx.compose.material3.TabRow(selectedTabIndex = selectedTabIndex) {
Not needed. IDE brought it in on copy paste. The import works

2024-10-04 18:05 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/internal/util/TabRow.kt
> +    tabItems: List<String> = listOf(stringResource(R.string.new_trace), stringResource(R.string.results)),
updated

2024-10-04 18:18 UTC, sorenoid approved these changes
LGTM, two more minor suggestions.

2024-10-04 18:18 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptionsScreen.kt
> +                TabRow(onBackToResults, selectedIndex = 0)
```suggestion
            TabRow(onBackToResults, 0)
```

2024-10-04 18:18 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +            TabRow(onBackToNewTrace, selectedIndex = 1)
```suggestion
            TabRow(onBackToNewTrace, 1)
```

2024-10-07 21:53 UTC, eri9000 approved these changes
LGTM
A few suggestions but otherwise 👍🏼

2024-10-07 21:53 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +            )
Would suggest moving this to `TabRow` as you do the same in both Result screen and Options screen

2024-10-07 23:03 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +            )
Reading this in the code here makes more sense, as we are adding the tabrow and the tabrow should not be adding additional space after it implicitly.

2024-10-07 23:04 UTC, merged