Adds error reporting
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #600
Opened 2024-10-02 22:55 UTC by eri9000

Related to issue: #4485

### Description:
- Recoverable errors will be show in a dialog and unrecoverable errors will be show at the top of the trace tool
### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-10-04 16:38 UTC, puneet-pdx commented
@eri9000 can you please the vTest for this PR

2024-10-04 21:48 UTC, puneet-pdx reviewed
@eri9000 some comments

2024-10-04 21:48 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    private fun processAndAddStartingPoint(feature: ArcGISFeature, mapPoint: Point): Boolean {
the code in the fun needs to be in a try catch where we need to catch the exception and show it as an error dialog.
We need to either have individual try/catches or one big one. 
I have not evaluated all the calls but I know that setting fraction along the edge can throw and can cause app crash
https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/600/files#diff-2a0351bcc4936ef223088b506a9cef807daec1126fd71e2ee015d70e89cc8e40R423

2024-10-04 21:48 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceNavigation.kt
> +                        if (traceState.trace()) {
the trace() can throw an exception are we catching all in the trace function ?

2024-10-09 16:48 UTC, puneet-pdx reviewed
@eri9000 few more comments.

2024-10-09 16:48 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceNavigation.kt
> +            val localContext = LocalContext.current
this isn not being used anywhere, could be removed.

2024-10-09 16:48 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    internal var currentError: Throwable? = null
this should have a backup property, which is settable only in the `TraceState`

private var _currentError: Throwable? = null
internal val currentError: Throwable? = _currentError

and add an internal setter for setting _currentError, setCurrentError(error: Throwable)

2024-10-09 16:48 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceErrorDialog.kt
> +internal fun TraceErrorDialog(message: String, onConfirmation: () -> Unit) {
we should pass the error here and retrieve the string in the fun
```Kotlin
@Composable
internal fun TraceErrorDialog(error: Throwable?, onConfirmation: () -> Unit) {
    val errorMessage = when (error) {
        is TraceToolException -> stringResource(error.traceError.messageId)
        else -> error?.message ?: "An error has occurred"
    }

AlertDialog(
....
        text = { Text(errorMessage) },
....       
            }
        }
    )
```

2024-10-09 16:48 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceNavigation.kt
> +            val localContext = LocalContext.current
I think we can just avoid retrieving the context here and getting the string. We can just pass the error enum to the `TraceErrorDialog` and retrieve the error string there with a single line `stringResource(error.errorId)`

2024-10-09 16:48 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceError.kt
> +internal class TraceToolException(val errorId: Int): Exception()
Instead of the `errorId` this should take just the `TraceError` 

`internal class TraceToolException(val traceError: TraceError): Exception()` 

it would simplify the invocation
```kotlin
throw TraceToolException(TraceError.NOT_ENOUGH_STARTING_POINTS_ONE)
```

2024-10-09 21:59 UTC, puneet-pdx approved these changes
@eri9000 two minor comments. Will not hold the PR for it.

2024-10-09 21:59 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceError.kt
> +        is TraceToolException -> getString(context, R.string.an_error_has_occurred)
This will always return the same error message
```suggestion
        is TraceToolException -> getString(context, this.traceError.resId))
```

2024-10-09 21:59 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceError.kt
> + * @param errorId The error id of the error thrown, used for localization.
this is not accurate. You can get rid of this and just modify the doc that includes the param in it

 * Exception class to represent the different [traceError] that can be thrown by the Trace tool.

2024-10-11 23:33 UTC, sorenoid requested changes
I think there is one small regression

2024-10-11 23:33 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/Trace.kt
> +            is InitializationStatus.Initializing -> {
This needs to handle the `NotInitialized` case and show a progress indicator. As you have it, it will show the NavHost. If the initialization gets hung, it will just show a blank screen forever.

2024-10-11 23:41 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/Trace.kt
> +            is InitializationStatus.Initializing -> {
Good catch, updated.

2024-10-14 21:00 UTC, sorenoid approved these changes

2024-10-14 23:09 UTC, merged