Puneet/4525 multiple results
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #601
Opened 2024-10-07 16:09 UTC by puneet-pdx

Related to issue: #

### Description:

### Summary of changes:

- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-10-09 19:37 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +        get() = _selectedTraceRun
```suggestion
    internal val selectedTraceRun: State<TraceRun?> = _selectedTraceRun
```

2024-10-11 22:48 UTC, eri9000 requested changes
@puneet-pdx 
I have some suggestions regarding how we are keeping track of the current trace result. 
See my comments.

2024-10-11 22:48 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    internal val selectedTraceRun: State<TraceRun?> = _selectedTraceRun
I am a bit confused on the need for 3 different variables to keep track of the "current trace result", `currentTraceRun`, `selectedTraceRun`, and `_selectedCompletedTraceIndex`.
I think you might be able to consolidate these 3 variables by just keeping track of the the index of the "current trace result".
Since we will want to update it when the user chooses to see another result, this has to be a mutable state so that it could be observed.  
 -> `internal var currentTraceResultIndex: MutableState<Int>`
This is possible because we already have a list of the `completedTraces`.
 When you need the current `TraceResult`, then you can call `completedTraces[currentTraceResultindex]`

2024-10-11 22:48 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    }
This could be simplified with only keeping track of the index: 
```suggestion
    internal fun selectNextCompletedTrace() {
        if (currentTraceResultIndex.value + 1 < _completedTraces.size) {
            currentTraceResultIndex.value += 1
        }
    }
```

2024-10-11 22:48 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    }
This could also be simplified by using the current index:
```suggestion
    internal fun selectPreviousCompletedTrace() {
        if (currentTraceResultIndex.value > 0) {
            currentTraceResultIndex.value -= 1
        }
    }
```

2024-10-11 22:48 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceNavigation.kt
>              TraceResultScreen(
Since you are keeping track of the index, you have two options here. Pass the index and the list and get the `selectedTraceRun` from the list OR get the `selectedTraceRun` here from the list and pass it along with the list `size`

2024-10-11 22:48 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +                )
this could be extracted to its own component: 
```kotlin
TraceResultPager(
    selectedTraceRunIndex: Int,
    traceResultsSize: Int,
    onSelectPreviousTraceResult: () -> Unit,
    onSelectNextTraceResult: () -> Unit
) {
```

2024-10-11 22:48 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +private fun getTraceCounterString(currentTraceResult: Int, totalTraceResults: Int): String {
If you extract the trace result pager, then you could inline this.

2024-10-14 19:29 UTC, eri9000 approved these changes
@puneet-pdx Good work, looks good to me. 
Just one question, but otherwise 👍🏼

2024-10-14 19:29 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    private var currentTraceRun: MutableState<TraceRun?> = mutableStateOf(null)
just wondering now that we don't use this in the UI if this needs to be a `State`?

2024-10-14 20:11 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    private var currentTraceRun: MutableState<TraceRun?> = mutableStateOf(null)
updated

2024-10-14 20:11 UTC, merged