Starting point details screen
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #604
Opened 2024-10-10 20:50 UTC by puneet-pdx

Related to issue: #

### Description:

### Summary of changes:

- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-10-11 19:06 UTC, sorenoid requested changes
Functionality looks good. I have some UI opinions...

2024-10-11 19:06 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                    .padding(10.dp, 3.dp),
It looks like this screen has differnt justification than the trace options screen. I suggest making them the same.

2024-10-11 19:06 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                    .padding(10.dp, 3.dp),
Also this should probably have the same border as the expandable cards.

2024-10-11 19:06 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                    imageVector = Icons.AutoMirrored.Default.ArrowBack,
This arrow is showing up as dark in dark mode. I'd expect a white arrow in dark mode.

2024-10-11 19:06 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                    imageVector = Icons.AutoMirrored.Default.ArrowBack,
(I know you didn't add it, but I think just changing it `Icons.AutoMirrored.Sharp.ArrowBack` will fix it.

2024-10-11 19:06 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +            Title(startingPoint.name, onZoomTo, onDelete)
Could use a little space below the Title.

2024-10-11 22:46 UTC, sorenoid commented
as discussed, UI feedback should just come from Rama rather than little things from me and little things from everyone else.

2024-10-11 22:46 UTC, sorenoid approved these changes

2024-10-14 21:26 UTC, rchintapalli commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                value = sliderValue,
can add padding 

```
                modifier = Modifier.padding(start = 10.dp, end = 10.dp),
```

2024-10-14 21:28 UTC, rchintapalli commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                .background(color = MaterialTheme.colorScheme.background)
Same as above, color and shape on background so that it doesn't blend into background color

```
.background(color = MaterialTheme.colorScheme.surfaceContainerHigh,
                    shape = RoundedCornerShape(15.dp))
                    ```

2024-10-14 21:29 UTC, rchintapalli commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                        .background(color = MaterialTheme.colorScheme.background),
```suggestion
                        .background(color = MaterialTheme.colorScheme. surfaceContainerHigh),
```

2024-10-14 21:30 UTC, rchintapalli commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                    imageVector = Icons.AutoMirrored.Default.ArrowBack,
See the same, so we can fix it

2024-10-14 21:33 UTC, rchintapalli reviewed
Some minor UI suggestions. Looks like this in my app after suggestions.

My Dark Theme:
![StartingPointScreenDark](https://github.com/user-attachments/assets/47509d68-9055-476a-8ba1-a6cb771d9d3c)

My Light Theme:

![StartingPointScreenLight](https://github.com/user-attachments/assets/81f8bf2d-7626-43e6-af61-f762211b094c)

2024-10-14 21:51 UTC, eri9000 requested changes
@puneet-pdx 
Good work, some suggestions.

2024-10-14 21:51 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/internal/util/TitleRow.kt
> +                        onClick = onZoomTo,
I am noticing a delay on the menu disappearing after clicking on the zoom to/delete buttons. 
You can set `expanded = false` here to make it disappear right away. 
```suggestion
                        onClick = {
                            expanded = false
                            onZoomTo()
                        },
```

2024-10-14 21:51 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/internal/util/TitleRow.kt
> +                        onClick = onDelete,
same suggestion as above

2024-10-14 21:51 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                        TerminalConfiguration(startingPoint, onTerminalSelected)
It seems that you're only using the `terminal.name` and `terminals` from `StartingPoint`, might be better to pass this instead of the `StartingPoint` object.

2024-10-14 21:51 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +private fun BackButton(
You can make this more reusable by passing the `title` as a parameter

2024-10-14 21:51 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
>  private fun FractionAlongEdgeSlider(startingPoint: StartingPoint, onFractionChanged: (StartingPoint, Float) -> Unit) {
Nitpick, you don't need to pass `startingPoint` here if you're just going to pass it back up again in your `onValueChanged`. You can hoist it up. 
```suggestion
private fun FractionAlongEdgeSlider(fractionAlongEdge: Float, onFractionChanged: (Float) -> Unit)
```

2024-10-14 21:51 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                    onFractionChanged(startingPoint, newValue)
```suggestion
                     onFractionChanged(newValue)
```

2024-10-14 21:51 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                        FractionAlongEdgeSlider(startingPoint, onFractionChanged)
Then you can replace the call as such: 
```suggestion
                        FractionAlongEdgeSlider(
                            fractionAlongEdge = startingPoint.utilityElement.fractionAlongEdge.toFloat(),
                            onFractionChanged = { newValue ->
                                onFractionChanged(startingPoint, newValue)
                            }
                        )
```

2024-10-15 00:35 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                        FractionAlongEdgeSlider(startingPoint, onFractionChanged)
I don't see the advantage in doing this. I like this call to be simple and all the functionality contained in the function.

2024-10-15 00:37 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
>  private fun FractionAlongEdgeSlider(startingPoint: StartingPoint, onFractionChanged: (StartingPoint, Float) -> Unit) {
I don't see the advantage of doing this, I like the function call being simple and the logic needed is contained in the fun displaying the data.

2024-10-15 00:40 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +                        TerminalConfiguration(startingPoint, onTerminalSelected)
Yes, but I am using rememberSavable to save the terminalName so it won't be re-read on orientation changes. Also I thought it was easy to understand the code when the values being used in the UI elements are being retrieved right where they are being used.

2024-10-15 18:35 UTC, eri9000 requested changes
@puneet-pdx 
Changes look good, one more comment.

2024-10-15 18:35 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/internal/util/TitleRow.kt
> +                    overflow = TextOverflow.Ellipsis
when the title is too long, i see the ellipsis `...` but it causes the `More` icon to disappear. I think you might be able to fix this by changing the row alignment.

2024-10-15 19:03 UTC, eri9000 approved these changes
Good work 👍🏼

2024-10-15 19:05 UTC, merged