Adds BackHandler actions
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #606
Opened 2024-10-11 19:22 UTC by eri9000

Related to issue: kotlin#4707

### Summary of changes:
- Defines the behavior for the BackHandler in each screen 
- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-10-11 23:15 UTC, sorenoid requested changes
this PR includes changes from the error handling PR.

2024-10-15 15:21 UTC, puneet-pdx commented
@eri9000 can you please run the vTest for this PR

2024-10-15 19:15 UTC, sorenoid approved these changes
works well. I think that adding a back handler to MainActivity to swallow back presses will be helpful for app stability, but isn't part of the component.

2024-10-17 18:44 UTC, puneet-pdx reviewed
@eri9000 few questions

2024-10-17 18:44 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +import androidx.compose.foundation.clickable
why are we not adding the backHandler in this screen ?

```Kotlin
 BackHandler {
        onBackPressed()
    }
```

2024-10-17 18:44 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceErrorDialog.kt
> -import androidx.core.content.ContextCompat.getString
Why are we not adding the backhandler in the error dialog ?

2024-10-17 19:59 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/StartingPointDetailsScreen.kt
> +import androidx.compose.foundation.clickable
Good catch, the StartingPointsDetailsScreen was added after this PR was created hence there was no back handler there. I have fixed this.

2024-10-17 20:00 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceErrorDialog.kt
> -import androidx.core.content.ContextCompat.getString
it isn't necessary because the `onDismissRequest` parameter of the `AlertDialog` already handles the dismissal of the dialog when the back button is pressed.

2024-10-17 20:03 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceErrorDialog.kt
> -import androidx.core.content.ContextCompat.getString
but we are not using navigation then, do we not have to worry about popping it from the backstack ?

2024-10-17 22:12 UTC, puneet-pdx approved these changes

2024-10-17 22:47 UTC, merged