Puneet/4521 feature results
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #608
Opened 2024-10-14 20:15 UTC by puneet-pdx

Related to issue: #

### Description:

### Summary of changes:

- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-10-17 19:20 UTC, eri9000 requested changes
@puneet-pdx 
Some initial comments.

2024-10-17 19:20 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceNavigation.kt
> +            require(selectedGroupName != null)
Not sure if this is the correct way to handle this as it could just throw an exception and potentially cause an app crash?
Could you just set a "default" name when it equals null?

2024-10-17 19:20 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/FeatureResultsDetailsScreen.kt
> +                                contentDescription = "zoom in",
this needs to be a string resource

2024-10-17 19:20 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    internal fun getAllElementsWithSelectedGroupName(): List<UtilityElement> {
this could be more modular if the `selectedGroupName` is passed in instead.

2024-10-17 20:40 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    internal suspend fun zoomToUtilityElement(utilityElement: UtilityElement) = runCatchingCancellable {
I don't think so. One is taking StartingPoint as a input and the other one takes a UtilityElement. For the Starting point we already have the Graphic that we need to zoom into. For the UtilityElement we don't we have to first get the feature from it and then the associated Graphic. 

>why is this one using geometry.extent but zoomToStartingPoint isn't?
the geometry returned from the UtilityElement feature could be of any type and could have an extent that encompasses all the geometries in a multipart.
For a Starting point, we know it is a point as we are creating it. I have changed it to be an extent as well.

2024-10-17 21:00 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceNavigation.kt
> +            require(selectedGroupName != null)
It is not going to be null. I have changed the default to empty string

2024-10-17 21:01 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/FeatureResultsDetailsScreen.kt
> +                                contentDescription = "zoom in",
can we tackle this in the whole sale change for all the contentDescriptions

2024-10-17 21:02 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +    internal fun getAllElementsWithSelectedGroupName(): List<UtilityElement> {
We are already holding on to the selectedGroupName in the viewModel, will seem redundant to pass it in.

2024-10-17 22:43 UTC, eri9000 reviewed
A few more suggestions

2024-10-17 23:33 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/FeatureResultsDetailsScreen.kt
> +                                contentDescription = "zoom in",
done

2024-10-18 15:13 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/internal/util/TitleRow.kt
>          Box {
As per our discussion, this suggestion does not help with positioning the title and the dropdown menu as we like.

2024-10-18 20:24 UTC, eri9000 approved these changes
LGTM

2024-10-21 21:17 UTC, sorenoid approved these changes
LGTM, I have a couple of minor suggestions.

2024-10-21 21:17 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/FeatureResultsDetailsScreen.kt
> +            )
nitpick: the `Spacer` and `Column` paramter indentation formatting is different. Can you please make them the same formatting? Generally, I think that the way `Spacer` is is more prevalent in Kotlin and Compose and is the way most of the other code in this new function is formatted.

2024-10-21 21:17 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/FeatureResultsDetailsScreen.kt
> +                                text = "${stringResource(R.string.object_id)}: ${utilityElement.objectId}",
this should use a stringResource format string so that it can be localized in RTL locales.
```suggestion
                                text = stringResource(R.string.object_id, utilityElement.objectId),
```

2024-10-21 22:02 UTC, merged