WIP
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #613
Opened 2024-10-16 20:01 UTC by puneet-pdx

Related to issue: #

### Description:

### Summary of changes:

- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-10-21 20:11 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> -    private val _currentScreen: MutableState<TraceNavRoute> = mutableStateOf(TraceNavRoute.TraceOptions)
with the navigation changes this is not being used anymore

2024-10-22 00:45 UTC, sorenoid requested changes
looks good overall. Just some minor suggestions.

2024-10-22 00:45 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +        val selectedTrace = _completedTraces[_selectedCompletedTraceIndex.value]
It seems like the SimpleMarkerSymbol added for a starting point should be removed here as well. But that is  probably better done in a separate issue.

2024-10-22 00:45 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/res/values/strings.xml
> +    <string name="clear_all_results_confirmation">All the trace results will be lost, proceed?</string>
```suggestion
    <string name="clear_all_results_confirmation">All trace results will be lost.</string>
```

2024-10-22 00:45 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +            }
```suggestion
            val selectedColor by remember(selectedTraceRunIndex) { mutableStateOf(selectedTraceRun.resultGraphicColor) }
```

2024-10-22 20:10 UTC, sorenoid approved these changes

2024-10-23 00:48 UTC, eri9000 requested changes
@puneet-pdx 
Good work, 
some suggestions

2024-10-23 00:48 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptionsScreen.kt
> +            ColorPickerRow(selectedColor, onColorChanged)
I don't think there's need for `ColorPickerRow` since it is just the same as `AdvancedOptionsRow`. 
The previous usage of `AdvancedOptions` worked ok

2024-10-23 00:48 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/ClearAllResultsDialog.kt
> +internal fun ClearAllResultsDialog(onConfirmation: () -> Unit, onDismiss: () -> Unit) {
```suggestion
internal fun ClearAllResultsDialog(onConfirmation: () -> Unit, onCancel: () -> Unit) {
```

2024-10-23 00:48 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +            if (traceResults.isEmpty()) {
why is this needed?
when there's no more results, you're already navigating to a different screen

2024-10-23 00:48 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +    )
Readability wise, this can be placed in TraceResultScreen() composable

2024-10-23 00:48 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +        padding = PaddingValues(horizontal = 4.dp)
No need for this additional padding, there is already padding being applied n the Color Picker

2024-10-23 01:16 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/ClearAllResultsDialog.kt
> +internal fun ClearAllResultsDialog(onConfirmation: () -> Unit, onDismiss: () -> Unit) {
The alertDialog calls it the dismiss button(with cancel as text ), and confirmation button (with OK text)
With that onConfirmation should also be called onOk. That didn't sit write with me. So I went with Android is calling the buttons

2024-10-23 01:23 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +            if (traceResults.isEmpty()) {
the result screen recomposes when the state of selectedTraceRunIndex changes to 0.

2024-10-23 01:31 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
> +        padding = PaddingValues(horizontal = 4.dp)
This is needed, without it the AdvancedOptions is smaller than the FeatureResults and FunctionResults.
It is applied in TraceOptionsScreen as well
https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/blob/feature-branches/utilitynetworktrace/toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceOptionsScreen.kt#L360

2024-10-23 17:46 UTC, eri9000 approved these changes
LGTM 👍🏼

2024-10-23 17:46 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/ui/TraceResultScreen.kt
>              val selectedTraceRun = traceResults[selectedTraceRunIndex]
remembering `selectedTraceRun` fixes the issue: 
```suggestion
            val selectedTraceRun = remember(selectedTraceRunIndex) {  traceResults[selectedTraceRunIndex]}
```

2024-10-23 17:56 UTC, merged