Highlight feature results
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #627
Opened 2024-10-25 20:44 UTC by puneet-pdx

Related to issue: #

### Description:

### Summary of changes:

- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-10-28 23:20 UTC, eri9000 approved these changes
LGTM

2024-10-28 23:20 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/TraceState.kt
> +                                featuresForElements.groupBy { it.featureTable?.layer as FeatureLayer }
i think this could be moved up to the if statement

2024-10-30 23:39 UTC, TADraeseke requested changes
Only high level comments:

- If I select a new trace, should all features de-select?

Tab selection issue repro:
- Have a couple trace results
- Tap new trace. Bottom menu correctly switches to trace configuration, but tab highlight at the top does not.
- Tap new trace again and switches to results.
- Tap new trace again and top tab and trace configuration correctly selected

2024-10-31 16:10 UTC, puneet-pdx commented
@TADraeseke 
>If I select a new trace, should all features de-select? 

I assume you are going from results tab to the new trace tab? In that case no all features should not de-select as the features on the map that are selected are showing the result that is selected. Once a new trace is done then its results are selected. We don't unselect the results as soon as new trace is navigated to as the user might not want to do a new trace and would like to go back to the results screen. 

>Tab selection issue repro:

Have a couple trace results
Tap new trace. Bottom menu correctly switches to trace configuration, but tab highlight at the top does not.
Tap new trace again and switches to results.
Tap new trace again and top tab and trace configuration correctly selected 

This [issue](https://devtopia.esri.com/runtime/kotlin/issues/4790) was fixed with a separate [PR](https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/622), this branch didn't have those changes. I have merged the feature branch to this one now. You should not see those issues.

2024-10-31 16:52 UTC, TADraeseke approved these changes
Nice! Looks good to me!

2024-10-31 19:30 UTC, merged