Add automated test for trace tool
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #640
Opened 2024-10-31 22:05 UTC by puneet-pdx

Related to issue: # https://devtopia.esri.com/runtime/kotlin/issues/4604

### Description:

adds automated test for Trace tool

### Summary of changes:

- Add a test scenario and a test for the trace tool

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link: https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/176/
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-11-02 01:46 UTC, sorenoid requested changes
looks great. just one question/suggestion.

2024-11-02 01:46 UTC, sorenoid commented on toolkit/utilitynetworks/src/androidTest/java/com/arcgismaps/toolkit/utilitynetworks/TraceToolTests.kt
> +        Thread.sleep(5000L)
why not just load them explicitly? This may fail.

2024-11-04 17:41 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/androidTest/java/com/arcgismaps/toolkit/utilitynetworks/TraceToolTests.kt
> +        Thread.sleep(5000L)
I guess the comment is misleading here. We are not waiting for the map to load but for the layers to be done drawing. The test was getting into a state where the map was loaded along with the utility layers so the Trace tool UI was functional but the layers in the map were still not done drawing, the test will perform an identify and will get no results back as the layer was not drawn yet. 
I have updated the comment and added a latch to wait here till we get a draw status completed here.

2024-11-04 20:24 UTC, sorenoid requested changes
sorry I missed a suggestion I'd like to make on Friday.

2024-11-04 20:24 UTC, sorenoid commented on toolkit/utilitynetworks/src/androidTest/java/com/arcgismaps/toolkit/utilitynetworks/TraceToolTestRunner.kt
> +
```suggestion
    internal val map: ArcGISMap = ArcGISMap(PortalItem(Portal.arcGISOnline(connection = Portal.Connection.Anonymous), itemId))
    internal val mapviewProxy: MapViewProxy = MapViewProxy()
    internal val graphicsOverlay: GraphicsOverlay = GraphicsOverlay()
    // Create a CountDownLatch to wait for the draw status change
    internal val drawStatusLatch = CountDownLatch(1)
```

I am sorry I didn't see this on Friday. It doesn't appear necessary to have backing fields for these internal properties, or computed getters.

2024-11-04 22:45 UTC, sorenoid approved these changes

2024-11-05 19:46 UTC, TADraeseke approved these changes
LGTM! Just FYI, see comment about emulated device

2024-11-05 19:46 UTC, TADraeseke commented on toolkit/utilitynetworks/src/androidTest/java/com/arcgismaps/toolkit/utilitynetworks/TraceToolTests.kt
> +        composeTestRule.waitUntilExactlyOneExists(
I hit this:

`androidx.compose.ui.test.ComposeTimeoutException: Condition (exactly 1 nodes match (Text + EditableText contains 'Underground Three Phase' (ignoreCase: false))) still not satisfied after 10000 ms
`

2024-11-05 19:46 UTC, TADraeseke commented on toolkit/utilitynetworks/src/androidTest/java/com/arcgismaps/toolkit/utilitynetworks/TraceToolTests.kt
> +        composeTestRule.waitUntilExactlyOneExists(
Increasing the time out doesn't fix the failure

2024-11-05 19:46 UTC, TADraeseke commented on toolkit/utilitynetworks/src/androidTest/java/com/arcgismaps/toolkit/utilitynetworks/TraceToolTests.kt
> +        composeTestRule.waitUntilExactlyOneExists(
Hmm, worked on my physical device (Samsung Galaxy A55 5G), but not on emulator (Pixel fold API 34)

2024-11-05 20:08 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/androidTest/java/com/arcgismaps/toolkit/utilitynetworks/TraceToolTests.kt
> +        composeTestRule.waitUntilExactlyOneExists(
@TADraeseke thanks. I will keep this in mind. The test is passing on the vTest device as well.

2024-11-05 20:08 UTC, merged

2024-11-05 20:10 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/androidTest/java/com/arcgismaps/toolkit/utilitynetworks/TraceToolTests.kt
> +        composeTestRule.waitUntilExactlyOneExists(
It might not be working on the emulator as screen point must have changed due to different screen size, leading to a different identify result and not returning the expected feature.