Adds Trace Container composable
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #641
Opened 2024-10-31 23:10 UTC by eri9000

Related to issue: kotlin#4867

### Summary of changes:
- Refactors `Trace` to separate UI from Navigation 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-10-31 23:12 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/Trace.kt
> - * A composable UI component to set up and run a [com.arcgismaps.utilitynetworks.UtilityNetwork.trace]
this import was not working

2024-10-31 23:14 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/Trace.kt
> +                is InitializationStatus.FailedToInitialize -> {
this additional case will only show an unrecoverable error, not the TraceOptions screen

2024-10-31 23:19 UTC, sorenoid requested changes
One question

2024-10-31 23:19 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/Trace.kt
> +        }
This seems out of place now. Shouldn't it be entirely within the `TraceContainer`? Is there a reason it must be passed as a parameter?

2024-10-31 23:42 UTC, eri9000 commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/Trace.kt
> +        }
I am thinking of `TraceContainer` as a `Scaffold`, where the `TopNavBar` is passed in. 
This also allows us to test the content independently from the tabRow and might make it easier to refactor it later without introducing other dependencies to `TraceContainer`.

2024-11-01 04:35 UTC, sorenoid commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/Trace.kt
> +        }
ok. should it be called `TraceScaffold` then?

2024-11-01 04:35 UTC, sorenoid approved these changes

2024-11-01 22:34 UTC, puneet-pdx commented
@eri9000 this refactor has changed how the circular progress indicator is being displayed. Before these changes it was in the middle of the component now it is at the top. Can we go back to how it was before.

**Before** 
https://github.com/user-attachments/assets/090978ba-5e7e-416f-9a1e-c6b64d5f3be8

**After**
https://github.com/user-attachments/assets/a75fe4d4-5912-4ce0-9a7f-7f610806de83

2024-11-01 22:35 UTC, puneet-pdx reviewed
@eri9000 We have a behavior change with this refactor.

2024-11-01 22:35 UTC, puneet-pdx commented on toolkit/utilitynetworks/src/main/java/com/arcgismaps/toolkit/utilitynetworks/Trace.kt
> + * A composable UI component to set up and run a [trace](https://developers.arcgis.com/kotlin/api-reference/arcgis-maps-kotlin/com.arcgismaps.utilitynetworks/-utility-network/trace.html?)
```suggestion
 * A composable UI component to set up and run a [trace](https://developers.arcgis.com/kotlin/api-reference/arcgis-maps-kotlin/com.arcgismaps.utilitynetworks/-utility-network/trace.html)
```

2024-11-04 22:04 UTC, puneet-pdx approved these changes

2024-11-04 22:23 UTC, merged