TableTop doc
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #644
Opened 2024-11-05 11:07 UTC by gunt0001

Related to issue: #

### Description:

### Summary of changes:

- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-11-07 14:08 UTC, hud10837 requested changes
Lots of great doc, just a few thoughts

2024-11-07 14:08 UTC, hud10837 commented on toolkit/ar/README.md
> +    - `translationFactor` - Determines how many meters the scene view translates as the device moves. A useful formula for determining this value is `translation factor = virtual content width / desi
```suggestion
    - `translationFactor` - Determines how many meters the scene camera moves as the device moves. A useful formula for determining this value is `translation factor = virtual content width / desired physical content width`. The virtual content width is the real-world size of the scene content and the desired physical content width is the physical table top width. The virtual content width is determined by the clipping distance in meters around the camera. For example, in order to setup a table top scene where scene data should be displayed within a 400 meter radius around the `arcGISSceneAnchor` and be placed on a table top that is 1 meter wide: `translation factor = 400 meter / 1 meter`.
```

2024-11-07 14:08 UTC, hud10837 commented on toolkit/ar/README.md
> +Note - the `TableTopSceneView` checks for availability of ARCore automatically. If ARCore is not supported by the device, the `TableTopSceneView` will fail to initialize with `TableTopSceneViewStatus
I think we should link to[ the Google docs](https://developers.google.com/ar/develop/java/enable-arcore#check_if_google_play_services_for_ar_is_installed) on how to prompt the user to install ARCore here.

2024-11-07 14:08 UTC, hud10837 commented on toolkit/ar/README.md
> +```
Should we also mention [this optional manifest entry](https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/blob/b0d472748ed7be7e14fa064e3a8583a155d7f4de/microapps/ArTabletopApp/app/src/main/AndroidManifest.xml#L56)? If an app is AR only it should be used.

2024-11-07 14:08 UTC, hud10837 commented on toolkit/ar/README.md
> +Pass a `onInitializationStatusChanged` callback to the `TableTopSceneView` composable function to get notified about initialization status changes.
```suggestion
Pass an `onInitializationStatusChanged` callback to the `TableTopSceneView` composable function to get notified about initialization status changes.
```

2024-11-07 14:08 UTC, hud10837 commented on toolkit/ar/screenshot.png
I find this picture a little confusing, it's hard to tell what it is displaying. I could help to take another picture outside or on a tabletop

2024-11-07 14:10 UTC, gunt0001 commented on microapps/ArTabletopApp/app/src/main/java/com/arcgismaps/toolkit/artabletopapp/screens/MainScreen.kt
> +                opacity = 0f
Yes, it hides the SceneView grid, which would otherwise be visible.

2024-11-08 13:31 UTC, hud10837 approved these changes
👍 Looks good and works well on my device

2024-11-08 13:56 UTC, merged