Update UtilityNetwork README and main README file
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #657
Opened 2024-11-07 22:51 UTC by puneet-pdx

Related to issue: # https://devtopia.esri.com/runtime/kotlin/issues/4912

### Description:

Updates the content of the readme files

### Summary of changes:

- Add screenshot of the Trace app
- Update the UtilityNetwork README file
- Update the project's readme file

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link: https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/193/
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-11-12 20:09 UTC, TADraeseke approved these changes
LGTM!

2024-11-12 22:40 UTC, sorenoid requested changes
Can you please add a README for the trace tool microapp? It is the only microapp without a README.

2024-11-13 22:14 UTC, sorenoid requested changes
just one small change. Please also consider the text that lists the styles used in the trace tool for its README.

2024-11-13 22:14 UTC, sorenoid commented on README.md
> +implementation(platform("com.esri:arcgis-maps-kotlin-toolkit-bom:200.6.0"))
```suggestion
implementation(platform("com.esri:arcgis-maps-kotlin-toolkit-bom:200.6.0"))
implementation("com.esri:arcgis-maps-kotlin-toolkit-ar")
```

2024-11-13 22:14 UTC, sorenoid commented on README.md
> +implementation(platform("com.esri:arcgis-maps-kotlin-toolkit-bom:200.6.0"))
The ar component now needs to be added here...

2024-11-13 22:55 UTC, puneet-pdx commented on README.md
> +implementation(platform("com.esri:arcgis-maps-kotlin-toolkit-bom:200.6.0"))
Not needed. Gunther merged changes to this file in his PR https://github.com/Esri/arcgis-maps-sdk-kotlin-toolkit/pull/664/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R56

2024-11-13 23:36 UTC, sorenoid approved these changes

2024-11-13 23:52 UTC, merged