Floor filter state initialization
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #678
Opened 2024-11-22 18:47 UTC by puneet-pdx

Related to issue: # https://devtopia.esri.com/runtime/kotlin/issues/3129

### Description:

- Provide a way to help the user figure out if the FloorFilterState is successfully loaded and is ready to select sites, facilities or levels

### Summary of changes:

- Add initializationStatus `State` that reports on the initialization status of the FloorFilterState. 
- Add InitializationStatus enum
- Deprecate the existing FloorFilterState() fun that takes coroutineScope, replace it with a new version that does not take the coroutineScope
- Remove init() from FloorFilterState and replace it with `public suspend fun initialize(): Result<Unit>`
- add `setSelectedValuesAppliedBeforeInitialization()` which sets the selected values that were applied before initialization by the user
- Refactor FloorFilter to use initializationStatus and to auto initialize FloorFilterState 
- Add `FloorFilterError` to localize errors defined in the component
- Add dependency on material icons to use the error icon 

The design does not specify how to report the errors and we had followed the previous implementation done by the indoors team and swift that did not report errors via UI. I have made changes so that the FloorFilter button will reflect when the FloorFilterState is initializing and when it fails to load.

https://github.com/user-attachments/assets/7e2f79a7-287f-4503-885b-03872eb32fab

![floorFilterError](https://github.com/user-attachments/assets/fd2e915a-ac7a-46ed-90b6-b15782b38cb1)

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link: ~https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/216/~
  - [x] https://runtime-kotlin.esri.com/view/vTest/job/vtest/job/toolkit/240/
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-11-22 22:06 UTC, puneet-pdx commented
For testing you can use these snippet in the test app
```Kotlin
val floorAwareWebMap by remember {
        mutableStateOf(
            ArcGISMap(
                PortalItem(
                    Portal("https://arcgis.com/"),
//                    "b4b599a43a474d3394" // invalid item id
//                    "471eb0bf37074b1fbb972b1da70fb310" // valid item id, no floor-aware data
                    "b4b599a43a474d33946cf0df526426f5" // valid item id, with floor-aware data
                )
            )
        )
    }
```

for auto setting of the selected values
```Kotlin
      floorFilterState.selectedLevelId = "GFC.WEST.G1"
//    floorFilterState.selectedSiteId = "GFC.RA"
//    floorFilterState.selectedFacilityId = "GCF.EAST.A"
//    floorFilterState.selectedFacilityId = "GFC.RA.L"
```
by using initializationStatus
```Kotlin
    val initializationStatus by floorFilterState.initializationStatus
    when (initializationStatus) {
        is InitializationStatus.FailedToInitialize -> {

        }
        InitializationStatus.Initialized -> {
            floorFilterState.selectedLevelId = "GFC.WEST.G1"
        }
        InitializationStatus.Initializing -> {

        }
        InitializationStatus.NotInitialized -> {

        }
    }
```

2024-11-26 00:20 UTC, shubham7109 requested changes
@puneet-pdx If I were to select a `floorFilterState.selectedLevelId = "GFC.WEST.GB"` on initialize, the floor filter is able to display the floor-map and the levels list. But then if were to open the `SiteFacilityButton` it displays the window with the correct site selected, but it does not show the facility as selected. 


Tested by setting the site/facility/level on initialize and the floor filter can display info on initialize. I added some change requests below:

2024-11-26 00:20 UTC, shubham7109 commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/FloorFilterState.kt
> +            selectedLevelId = temp
I'm not sure if I understand why the internal `_selectedLevelId` is being diverted to `null` here. 
```suggestion
            selectedLevelId = _selectedLevelId
```

2024-11-26 00:20 UTC, shubham7109 commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/FloorFilter.kt
> +                    Log.e("FloorFilter", errorMessage)
```suggestion
                    Log.e("FloorFilterException", errorMessage)
```

2024-11-26 00:20 UTC, shubham7109 commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/FloorFilter.kt
> +                        )
This should either be an `IconButton` or the `Modifier.clickable` should be part of the parent `Box`.

2024-11-26 00:20 UTC, shubham7109 commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/FloorFilter.kt
> +                            tint = MaterialTheme.colorScheme.primary
Maybe we should use the error scheme here? 
```suggestion
                            tint = MaterialTheme.colorScheme.error
```

2024-11-26 00:20 UTC, shubham7109 commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/FloorFilter.kt
> +            return
This was previously `return@Surface`
```suggestion
            return@Column
```

2024-11-26 20:28 UTC, puneet-pdx commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/FloorFilter.kt
> +                    Log.e("FloorFilter", errorMessage)
The error is coming from FloorFilter so the TAG should say so

2024-11-26 20:38 UTC, puneet-pdx commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/FloorFilterState.kt
> +            selectedLevelId = temp
We have a check were we don't set the selectedLevelId to a new value if it is the same as the old one. This logic caches the old value, sets the backing property to null and resets the selectedLevelId for setting the same value again

2024-11-26 22:49 UTC, puneet-pdx commented on toolkit/indoors/src/main/java/com/arcgismaps/toolkit/indoors/FloorFilterState.kt
> +    public val initializationStatus: State<InitializationStatus>
I remember having a discussion about not wanting to use SDK types in the toolkit. Also I think initialization makes more sense than load for FloorFilterState. 
Regarding this being a State, I think we are moving more towards Android compose paradigms in the Toolkit. StateFlow in the Kotlin API makes sense.
@sorenoid thoughts ?

2024-11-26 23:16 UTC, puneet-pdx commented
>@puneet-pdx If I were to select a floorFilterState.selectedLevelId = "GFC.WEST.GB" on initialize, the floor filter is able to display the floor-map and the levels list. But then if were to open the SiteFacilityButton it displays the window with the correct site selected, but it does not show the facility as selected.

@shubham7109 this is something that is not supported. As if were to do it, it would break the workflow of the UI based component which goes with the linear flow of select a site, then select a facility and then select a level.
Selecting a site resets the previous facility and level that was selected, then the user will select the facility and the level they would want to traverse. So at all times selectedSite, selectedFacility and selectedLevel return the correct values.

Here we are giving the user an option to bypass the usual flow to traverse the facility and to be able to select the starting level/facility/site on the map, the UI updating is not a part of it. 
https://devtopia.esri.com/runtime/common-toolkit/blob/main/designs/FloorFilter/FloorFilter.md
If we were to take the logic out to not reset the facility when site is updated then the Selected facility and site will return stale values, I don't think that will that be acceptable.

2024-12-02 17:00 UTC, shubham7109 approved these changes
@puneet-pdx Thanks for the explaination and the initialization fix works well as you have described. Looks good to me 👍

2024-12-09 17:08 UTC, sorenoid commented
@puneet-pdx can you please merge in v.next and address lint errors in this vTest? https://runtime-kotlin.esri.com/view/vTest/job/vtest/job/toolkit/236/parsed_console/

2024-12-09 21:11 UTC, puneet-pdx commented
@sorenoid updated.
https://runtime-kotlin.esri.com/view/vTest/job/vtest/job/toolkit/240/

2024-12-10 01:03 UTC, sorenoid approved these changes

2024-12-10 01:37 UTC, merged