Update dependencies
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #684
Opened 2024-12-05 17:57 UTC by puneet-pdx

Related to issue: #

### Description:

### Summary of changes:

- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-12-05 22:42 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/GeoViewScope.kt
> -            }
Resolves Lint error 

Using Modifier.then with a Modifier factory function with an implicit receiver More... (⌘F1) 
Inspection info: Calling a Modifier factory function with an implicit receiver inside Modifier.then will result in the receiver (this) being added twice to the chain. For example, fun Modifier.myModifier() = this.then(otherModifier()) - the implementation of factory functions such as Modifier.otherModifier() will internally call this.then(...) to chain the provided modifier with their implementation. When you expand this.then(otherModifier()), it becomes: this.then(this.then(OtherModifierImplementation)) - so you can see that this is included twice in the chain, which results in modifiers such as padding being applied twice, for example. Instead, you should either remove the then() and directly chain the factory function on the receiver, this.otherModifier(), or add the empty Modifier as the receiver for the factory, such as this.then(Modifier.otherModifier())  Issue id: SuspiciousModifierThen Vendor: Jetpack Compose Identifier: androidx.compose.ui Feedback: https://issuetracker.google.com/issues/new?component=612128

2024-12-05 22:43 UTC, puneet-pdx commented on toolkit/geoview-compose/src/main/java/com/arcgismaps/toolkit/geoviewcompose/GeoViewScope.kt
>      minSize: DpSize
Resolves Lint error 

Using Modifier.then with a Modifier factory function with an implicit receiver More... (⌘F1) 
Inspection info: Calling a Modifier factory function with an implicit receiver inside Modifier.then will result in the receiver (this) being added twice to the chain. For example, fun Modifier.myModifier() = this.then(otherModifier()) - the implementation of factory functions such as Modifier.otherModifier() will internally call this.then(...) to chain the provided modifier with their implementation. When you expand this.then(otherModifier()), it becomes: this.then(this.then(OtherModifierImplementation)) - so you can see that this is included twice in the chain, which results in modifiers such as padding being applied twice, for example. Instead, you should either remove the then() and directly chain the factory function on the receiver, this.otherModifier(), or add the empty Modifier as the receiver for the factory, such as this.then(Modifier.otherModifier())  Issue id: SuspiciousModifierThen Vendor: Jetpack Compose Identifier: androidx.compose.ui Feedback: https://issuetracker.google.com/issues/new?component=612128

2024-12-06 22:00 UTC, TADraeseke approved these changes
Tested on a few different scene/map micro apps. All looks fine!

2024-12-09 23:47 UTC, eri9000 requested changes
@puneet-pdx 
I am getting an error when building the project. It seems that some of the libraries are not compatible with `MircroapsLib->compilesdk = 34`. Changing it to 35 seems to fix it

2024-12-10 19:01 UTC, eri9000 approved these changes

2024-12-10 21:16 UTC, merged