Update deprecation
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #690
Opened 2024-12-11 21:15 UTC by puneet-pdx

Related to issue: #

### Description:

### Summary of changes:

- 

### Pre-merge Checklist

- a [vTest](https://runtime-kotlin.esri.com/view/all/job/vtest/job/toolkit/) Job for this PR has been run
  - [ ] link:
- Unit and/or integration tests have been added to exercise this PR's logic, and the tests are passing:
  - [ ] Yes
  - [ ] No

2024-12-17 18:38 UTC, TADraeseke approved these changes
Tested on all the microapps affected. All LGTM!

2024-12-18 17:53 UTC, sorenoid requested changes
The compiler flags for context receivers are no longer necessary anywhere but in the composable map module. Can you please remove those rather than update them?

2024-12-18 17:53 UTC, sorenoid commented on microapps/CompassApp/app/build.gradle.kts
> +    compilerOptions {
this can be removed since the compass no longer uses the deprecated composable map

2024-12-18 17:53 UTC, sorenoid commented on microapps/FeatureFormsApp/app/build.gradle.kts
> +    compilerOptions {
this can be removed since the feature forms no longer uses the deprecated composable map

2024-12-18 17:53 UTC, sorenoid commented on microapps/FeatureFormsApp/app/build.gradle.kts
> +    compilerOptions {
will not mention again for further usage -- they should all be removed, except for the one in the deprecated composable map.

2024-12-18 17:53 UTC, sorenoid commented on toolkit/composable-map/build.gradle.kts
> +    compilerOptions {
needs to be kept.

2024-12-18 23:02 UTC, puneet-pdx commented on microapps/FeatureFormsApp/app/build.gradle.kts
> +    compilerOptions {
I have removed all compiler flags for context receivers (except the one in composable map)

2024-12-19 20:21 UTC, sorenoid approved these changes
thanks for updating all the context receiver usage

2024-12-19 21:34 UTC, merged