consume core
Esri/arcgis-maps-sdk-kotlin-toolkit pull request #90
Opened 2023-08-08 23:22 UTC by sorenoid

the core changes for this branch to work will be in the daily build as of the noon build on Wednesday August 9, build 200.3.0-3960

this branch contains 
* the code to use the runtime API for constructing of forms objects from REST JSON data.
* the gradle code to get the build of the Kotlin SDK from mavenLocal

once we exit branch to release, we can rely on the regular Kotlin SDK builds to get the SDK. I'll make another PR at that point to remove all the extra maven stuff.

To use this branch, it is necessary to build the SDK locally with the main branch of runtimecore. There are no automated builds of this during branch to release. There are, however automated builds of runtimecore's main, so we can use those.

Instructions for using this branch:

* in the folder  on your filesystem containing kotlin, runtimecore, etc, replace the output folder with this output folder in this archive (warning: huge folder) smb://runtime.esri.com/android/rtc/200.3.0/last_good
* to reduce the size issues: just copy output/android_arm64_release to the appropriate local folder. arm64 is needed for running on an arm64 device or emulator on M2 Mac

 * in the folder on your filesystem containing kotlin, runtimecore, etc, replace the buildnum folder with the buildnum folder in this archive. this should be quick.

build libruntimecore_kotlin.so (expected time: 1 minute):
checkout main of runtimecore and kotlin
run the following:

```bash
#!/bin/bash
# cd to runtimecore...
./runtimecore_scripts/scripts/create_build.sh -p android -a android_arm64_release -u -n
./runtimecore_scripts/scripts/build.sh -p android -a android_arm64_release -n -c
```

ensure all code generation is turned on in the kotlin repo (gradle.properties) and publishToMavenLocal.
checkout toolkit branch sor10874/consume-core (or feature-branches/forms after the consume core branch is merged)

important: change the sdkBuildNum in the toolkit's gradle.properties file to match the number in the buildnum folder mentioned above.

build and run (must run to verify!)

2023-08-15 23:27 UTC, kaushikrw requested changes
After battling with core, I was able to finally build at test with the `3965` build. `3960` did not work. It's good to finally see the api in the sdk. I did have some thoughts mentioned below

2023-08-16 03:34 UTC, sorenoid commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
> +/**
I would normally not want to do that, as files only for the purpose of extensions [are considered bad Kotlin style](https://kotlinlang.org/docs/coding-conventions.html#source-file-organization). And I am concerned that if we have a file called `Extensions.kt` or something similar it might be added to in the future. So I would like to call the file something else and put a big comment in there saying it is only for the purpose of prototyping core functionality. I called in `CorePrototypes.kt`.

2023-08-16 16:06 UTC, kaushikrw commented on toolkit/featureforms/src/main/java/com/arcgismaps/toolkit/featureforms/components/text/FormTextFieldState.kt
> +/**
Ah I see. Good to know!

2023-08-16 18:42 UTC, kaushikrw approved these changes
LGTM!

2023-08-16 19:21 UTC, sorenoid commented
thanks @kaushikrw merging. We should be mindful that merging v.next into this feature branch will likely have conflicts with the gradle.properties changes in this PR. When daily builds resume, we can resolve those conflicts using v.next

2023-08-16 19:22 UTC, merged